//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acepto los.
        /// </summary>
        public static string Agree_Text {
            get {
                return ResourceManager.GetString("Agree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noticias anteriores.
        /// </summary>
        public static string Archive_Text {
            get {
                return ResourceManager.GetString("Archive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar.
        /// </summary>
        public static string Btn_Comprar {
            get {
                return ResourceManager.GetString("Btn_Comprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contáctanos.
        /// </summary>
        public static string Btn_Contactanos {
            get {
                return ResourceManager.GetString("Btn_Contactanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planes a tu medida aquí.
        /// </summary>
        public static string Btn_Planes {
            get {
                return ResourceManager.GetString("Btn_Planes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string Button_Continue {
            get {
                return ResourceManager.GetString("Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar muestra.
        /// </summary>
        public static string Button_Download {
            get {
                return ResourceManager.GetString("Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa a tu cuenta en Veritrade.
        /// </summary>
        public static string Button_GoHome {
            get {
                return ResourceManager.GetString("Button_GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar.
        /// </summary>
        public static string Button_Pay {
            get {
                return ResourceManager.GetString("Button_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string Close_Text {
            get {
                return ResourceManager.GetString("Close_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Le enviaremos un &lt;span&gt;correo electrónico&lt;/span&gt; con la confirmación y los datos de su compra.
        /// </summary>
        public static string Compra_Confirmacion_Mensaje {
            get {
                return ResourceManager.GetString("Compra_Confirmacion_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Gracias por tu &lt;span&gt;Compra!&lt;/span&gt;.
        /// </summary>
        public static string Compra_Confirmacion_Titulo {
            get {
                return ResourceManager.GetString("Compra_Confirmacion_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string Compra_Pedido_Direccion {
            get {
                return ResourceManager.GetString("Compra_Pedido_Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Más IGV.
        /// </summary>
        public static string Compra_Pedido_Igv {
            get {
                return ResourceManager.GetString("Compra_Pedido_Igv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razón Social.
        /// </summary>
        public static string Compra_Pedido_RazonSocial {
            get {
                return ResourceManager.GetString("Compra_Pedido_RazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruc.
        /// </summary>
        public static string Compra_Pedido_Ruc {
            get {
                return ResourceManager.GetString("Compra_Pedido_Ruc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impuesto a las ventas (sólo en NY).
        /// </summary>
        public static string Compra_Pedido_Tax {
            get {
                return ResourceManager.GetString("Compra_Pedido_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículo.
        /// </summary>
        public static string Compra_Pedido_Titulo01 {
            get {
                return ResourceManager.GetString("Compra_Pedido_Titulo01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen.
        /// </summary>
        public static string Compra_Pedido_Titulo02 {
            get {
                return ResourceManager.GetString("Compra_Pedido_Titulo02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string Compra_Pedido_Titulo03 {
            get {
                return ResourceManager.GetString("Compra_Pedido_Titulo03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string Compra_Pedido_Total {
            get {
                return ResourceManager.GetString("Compra_Pedido_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compra.
        /// </summary>
        public static string Compra_Text {
            get {
                return ResourceManager.GetString("Compra_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su Pedido.
        /// </summary>
        public static string Compra_Titulo01 {
            get {
                return ResourceManager.GetString("Compra_Titulo01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registre su Usuario en Veritrade.
        /// </summary>
        public static string Compra_Titulo02 {
            get {
                return ResourceManager.GetString("Compra_Titulo02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de su pago.
        /// </summary>
        public static string Compra_Titulo03 {
            get {
                return ResourceManager.GetString("Compra_Titulo03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usted ya cuenta con un plan vigente, cualquier duda sobre nuestros planes &lt;a class=&quot;contactenos&quot;&gt;contáctenos&lt;/a&gt;.
        /// </summary>
        public static string Compra_Verificacion_Mensaje {
            get {
                return ResourceManager.GetString("Compra_Verificacion_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificación de Usuario.
        /// </summary>
        public static string Compra_Verificacion_Titulo {
            get {
                return ResourceManager.GetString("Compra_Verificacion_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su Usuario y/o Contraseña no han sido ingresados correctamente..
        /// </summary>
        public static string desc_title1 {
            get {
                return ResourceManager.GetString("desc_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al enviar el correo.
        /// </summary>
        public static string desc_title10 {
            get {
                return ResourceManager.GetString("desc_title10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor vuelva a intentarlo..
        /// </summary>
        public static string desc_title2 {
            get {
                return ResourceManager.GetString("desc_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si olvidó su Usuario y/ o Clave, por favor .
        /// </summary>
        public static string desc_title3 {
            get {
                return ResourceManager.GetString("desc_title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pude ingresar debido a que su usuario se encuentra Inactivo en Veritrade..
        /// </summary>
        public static string desc_title4 {
            get {
                return ResourceManager.GetString("desc_title4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si desea activarlo, por favor.
        /// </summary>
        public static string desc_title5 {
            get {
                return ResourceManager.GetString("desc_title5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, este usuario no tiene acceso desde este país..
        /// </summary>
        public static string desc_title6 {
            get {
                return ResourceManager.GetString("desc_title6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si tiene una consulta, por favor .
        /// </summary>
        public static string desc_title7 {
            get {
                return ResourceManager.GetString("desc_title7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si Ud. aún no es cliente de Veritrade, inicie su: .
        /// </summary>
        public static string desc_title8 {
            get {
                return ResourceManager.GetString("desc_title8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , por favor .
        /// </summary>
        public static string desc_title9 {
            get {
                return ResourceManager.GetString("desc_title9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Digite el nombre de una empresa.
        /// </summary>
        public static string Empresas_Buscar_Content_Subtitle {
            get {
                return ResourceManager.GetString("Empresas_Buscar_Content_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de comercio exterior de &lt;br&gt; &lt;span&gt;latinoamerica&lt;/span&gt; y el &lt;span&gt;mundo&lt;/span&gt;.
        /// </summary>
        public static string Empresas_Buscar_Content_Title {
            get {
                return ResourceManager.GetString("Empresas_Buscar_Content_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Empresas.
        /// </summary>
        public static string Empresas_Buscar_Seo_Description {
            get {
                return ResourceManager.GetString("Empresas_Buscar_Seo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Empresas.
        /// </summary>
        public static string Empresas_Buscar_Seo_Title {
            get {
                return ResourceManager.GetString("Empresas_Buscar_Seo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string Field_Company_Text {
            get {
                return ResourceManager.GetString("Field_Company_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string Field_Country_Text {
            get {
                return ResourceManager.GetString("Field_Country_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string Field_Email_Text {
            get {
                return ResourceManager.GetString("Field_Email_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail (Usuario).
        /// </summary>
        public static string Field_EmailUser_Text {
            get {
                return ResourceManager.GetString("Field_EmailUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string Field_FirstName_Text {
            get {
                return ResourceManager.GetString("Field_FirstName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Completo.
        /// </summary>
        public static string Field_Fullname_Text {
            get {
                return ResourceManager.GetString("Field_Fullname_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string Field_LastNames_Text {
            get {
                return ResourceManager.GetString("Field_LastNames_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje.
        /// </summary>
        public static string Field_Message_Text {
            get {
                return ResourceManager.GetString("Field_Message_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre y Apellidos.
        /// </summary>
        public static string Field_Names_Text {
            get {
                return ResourceManager.GetString("Field_Names_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string Field_Phone_Text {
            get {
                return ResourceManager.GetString("Field_Phone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los derechos reservados.
        /// </summary>
        public static string Footer_AllRightsReserved {
            get {
                return ResourceManager.GetString("Footer_AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail.
        /// </summary>
        public static string Footer_Email {
            get {
                return ResourceManager.GetString("Footer_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfonos.
        /// </summary>
        public static string Footer_Phone {
            get {
                return ResourceManager.GetString("Footer_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búscanos en.
        /// </summary>
        public static string Footer_Searchby {
            get {
                return ResourceManager.GetString("Footer_Searchby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mapa del sitio.
        /// </summary>
        public static string Footer_SiteMap {
            get {
                return ResourceManager.GetString("Footer_SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Términos y condiciones.
        /// </summary>
        public static string Footer_TermsConditions {
            get {
                return ResourceManager.GetString("Footer_TermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa.
        /// </summary>
        public static string FreeTrial_Button_Send {
            get {
                return ResourceManager.GetString("FreeTrial_Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 
        ///	  
        ///		&lt;p&gt;Con &lt;strong&gt;Veritrade&lt;/strong&gt; accede a:&lt;/p&gt;
        ///                    &lt;ul class=&quot;ul-puntos-verdes&quot;&gt;
        ///                      &lt;li&gt;Información de nuevos clientes, proveedores y precios de productos.&lt;/li&gt;
        ///                      &lt;li&gt;Datos de tu competencia.&lt;/li&gt;
        ///                      &lt;li&gt;Oportunidades de negocio.&lt;/li&gt;
        ///                    &lt;/ul&gt;
        ///	 
        ///	.
        /// </summary>
        public static string FreeTrial_Content_Slide_01 {
            get {
                return ResourceManager.GetString("FreeTrial_Content_Slide_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La plataforma digital de comercio exterior para hacer crecer tu negocio..
        /// </summary>
        public static string FreeTrial_Title_Slide_01 {
            get {
                return ResourceManager.GetString("FreeTrial_Title_Slide_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de nuevos clientes, proveedores y precios de productos..
        /// </summary>
        public static string FreeTrial_Title_Slide_02 {
            get {
                return ResourceManager.GetString("FreeTrial_Title_Slide_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de la competencia..
        /// </summary>
        public static string FreeTrial_Title_Slide_03 {
            get {
                return ResourceManager.GetString("FreeTrial_Title_Slide_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oportunidades de negocio..
        /// </summary>
        public static string FreeTrial_Title_Slide_04 {
            get {
                return ResourceManager.GetString("FreeTrial_Title_Slide_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Estás a un paso de hacer crecer tu negocio!.
        /// </summary>
        public static string FreeTrial_Title01 {
            get {
                return ResourceManager.GetString("FreeTrial_Title01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicita nuestra prueba gratis.
        /// </summary>
        public static string FreeTrial_Title02 {
            get {
                return ResourceManager.GetString("FreeTrial_Title02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string Home_Content_Title01 {
            get {
                return ResourceManager.GetString("Home_Content_Title01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bases de Datos actualizadas al:.
        /// </summary>
        public static string Home_Content_Title02 {
            get {
                return ResourceManager.GetString("Home_Content_Title02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver todos los Países &gt;.
        /// </summary>
        public static string Home_Countries_Button {
            get {
                return ResourceManager.GetString("Home_Countries_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestros Clientes.
        /// </summary>
        public static string Home_Modal_Clientes_Title {
            get {
                return ResourceManager.GetString("Home_Modal_Clientes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizaciones de Base de Datos.
        /// </summary>
        public static string Home_Modal_Pais_Title {
            get {
                return ResourceManager.GetString("Home_Modal_Pais_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida arancelaria.
        /// </summary>
        public static string Home_Search_Cbo_Item01 {
            get {
                return ResourceManager.GetString("Home_Search_Cbo_Item01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción comercial.
        /// </summary>
        public static string Home_Search_Cbo_Item02 {
            get {
                return ResourceManager.GetString("Home_Search_Cbo_Item02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la empresa.
        /// </summary>
        public static string Home_Search_Company {
            get {
                return ResourceManager.GetString("Home_Search_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interesado en (*).
        /// </summary>
        public static string Home_Search_Item01 {
            get {
                return ResourceManager.GetString("Home_Search_Item01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Régimen (*).
        /// </summary>
        public static string Home_Search_Item02 {
            get {
                return ResourceManager.GetString("Home_Search_Item02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar la búsqueda por.
        /// </summary>
        public static string Home_Search_Item03 {
            get {
                return ResourceManager.GetString("Home_Search_Item03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importaciones.
        /// </summary>
        public static string Home_Search_Radio_Item01 {
            get {
                return ResourceManager.GetString("Home_Search_Radio_Item01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportaciones.
        /// </summary>
        public static string Home_Search_Radio_Item02 {
            get {
                return ResourceManager.GetString("Home_Search_Radio_Item02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por Empresa.
        /// </summary>
        public static string Home_Search_Tab01 {
            get {
                return ResourceManager.GetString("Home_Search_Tab01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda Avanzada.
        /// </summary>
        public static string Home_Search_Tab02 {
            get {
                return ResourceManager.GetString("Home_Search_Tab02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver más &gt;.
        /// </summary>
        public static string Home_Service_Button {
            get {
                return ResourceManager.GetString("Home_Service_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deseo factura.
        /// </summary>
        public static string Invoice_Text {
            get {
                return ResourceManager.GetString("Invoice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Últimas búsquedas.
        /// </summary>
        public static string LastestSearch {
            get {
                return ResourceManager.GetString("LastestSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Últimas noticias.
        /// </summary>
        public static string LatestNews {
            get {
                return ResourceManager.GetString("LatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollado para.
        /// </summary>
        public static string LoginDevelopedLabel {
            get {
                return ResourceManager.GetString("LoginDevelopedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string LoginForgotLabel {
            get {
                return ResourceManager.GetString("LoginForgotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chrome, IE9, Edge y Firefox.
        /// </summary>
        public static string LoginNavegadoresLabel {
            get {
                return ResourceManager.GetString("LoginNavegadoresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string LoginPasswordLabel {
            get {
                return ResourceManager.GetString("LoginPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a He leído y estoy de acuerdo con los.
        /// </summary>
        public static string LoginTerminosLabel {
            get {
                return ResourceManager.GetString("LoginTerminosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a Veritrade.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string LoginUserLabel {
            get {
                return ResourceManager.GetString("LoginUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario y password no pueden contener los siguientes caracteres.
        /// </summary>
        public static string LoginValidated_Characters {
            get {
                return ResourceManager.GetString("LoginValidated_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su contraseña.
        /// </summary>
        public static string LoginValidated_Pwd {
            get {
                return ResourceManager.GetString("LoginValidated_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe aceptar los t\u00E9rminos y condiciones.
        /// </summary>
        public static string LoginValidated_Terms {
            get {
                return ResourceManager.GetString("LoginValidated_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su usuario.
        /// </summary>
        public static string LoginValidated_User {
            get {
                return ResourceManager.GetString("LoginValidated_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A quiénes ayudamos.
        /// </summary>
        public static string MenuItem01 {
            get {
                return ResourceManager.GetString("MenuItem01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importadores.
        /// </summary>
        public static string MenuItem01_SubItem01 {
            get {
                return ResourceManager.GetString("MenuItem01_SubItem01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportadores.
        /// </summary>
        public static string MenuItem01_SubItem02 {
            get {
                return ResourceManager.GetString("MenuItem01_SubItem02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marketing y ventas.
        /// </summary>
        public static string MenuItem01_SubItem03 {
            get {
                return ResourceManager.GetString("MenuItem01_SubItem03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compradores locales.
        /// </summary>
        public static string MenuItem01_SubItem04 {
            get {
                return ResourceManager.GetString("MenuItem01_SubItem04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analistas.
        /// </summary>
        public static string MenuItem01_SubItem05 {
            get {
                return ResourceManager.GetString("MenuItem01_SubItem05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operadores logísticos.
        /// </summary>
        public static string MenuItem01_SubItem06 {
            get {
                return ResourceManager.GetString("MenuItem01_SubItem06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cómo te ayudamos.
        /// </summary>
        public static string MenuItem02 {
            get {
                return ResourceManager.GetString("MenuItem02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Demo.
        /// </summary>
        public static string MenuItem03 {
            get {
                return ResourceManager.GetString("MenuItem03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Países.
        /// </summary>
        public static string MenuItem04 {
            get {
                return ResourceManager.GetString("MenuItem04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planes y Precios.
        /// </summary>
        public static string MenuItem05 {
            get {
                return ResourceManager.GetString("MenuItem05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blog.
        /// </summary>
        public static string MenuItem06 {
            get {
                return ResourceManager.GetString("MenuItem06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contáctenos.
        /// </summary>
        public static string MenuItem07 {
            get {
                return ResourceManager.GetString("MenuItem07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string MenuItem08 {
            get {
                return ResourceManager.GetString("MenuItem08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar empresa.
        /// </summary>
        public static string MenuItem09 {
            get {
                return ResourceManager.GetString("MenuItem09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Producto.
        /// </summary>
        public static string MenuItem10 {
            get {
                return ResourceManager.GetString("MenuItem10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enero.
        /// </summary>
        public static string Mes01 {
            get {
                return ResourceManager.GetString("Mes01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Febrero.
        /// </summary>
        public static string Mes02 {
            get {
                return ResourceManager.GetString("Mes02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marzo.
        /// </summary>
        public static string Mes03 {
            get {
                return ResourceManager.GetString("Mes03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abril.
        /// </summary>
        public static string Mes04 {
            get {
                return ResourceManager.GetString("Mes04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayo.
        /// </summary>
        public static string Mes05 {
            get {
                return ResourceManager.GetString("Mes05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Junio.
        /// </summary>
        public static string Mes06 {
            get {
                return ResourceManager.GetString("Mes06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Julio.
        /// </summary>
        public static string Mes07 {
            get {
                return ResourceManager.GetString("Mes07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agosto.
        /// </summary>
        public static string Mes08 {
            get {
                return ResourceManager.GetString("Mes08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Septiembre.
        /// </summary>
        public static string Mes09 {
            get {
                return ResourceManager.GetString("Mes09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Octubre.
        /// </summary>
        public static string Mes10 {
            get {
                return ResourceManager.GetString("Mes10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noviembre.
        /// </summary>
        public static string Mes11 {
            get {
                return ResourceManager.GetString("Mes11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diciembre.
        /// </summary>
        public static string Mes12 {
            get {
                return ResourceManager.GetString("Mes12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Más leidos.
        /// </summary>
        public static string Most_Reads {
            get {
                return ResourceManager.GetString("Most_Reads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar PDF.
        /// </summary>
        public static string Pdf_text {
            get {
                return ResourceManager.GetString("Pdf_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planes Veritrade.
        /// </summary>
        public static string Planes_Veritrade {
            get {
                return ResourceManager.GetString("Planes_Veritrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;small&gt;Detalles de nuestros&lt;/small&gt; Planes.
        /// </summary>
        public static string Plans_Details_Title {
            get {
                return ResourceManager.GetString("Plans_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;small&gt;Planes&lt;/small&gt; Veritrade.
        /// </summary>
        public static string Plans_Title {
            get {
                return ResourceManager.GetString("Plans_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paises.
        /// </summary>
        public static string Plans_Title_Countries {
            get {
                return ResourceManager.GetString("Plans_Title_Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresos y Descargas.
        /// </summary>
        public static string Plans_Title_Downloads {
            get {
                return ResourceManager.GetString("Plans_Title_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plantillas de Excel.
        /// </summary>
        public static string Plans_Title_Excel {
            get {
                return ResourceManager.GetString("Plans_Title_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favoritos y Grupos.
        /// </summary>
        public static string Plans_Title_Favorites {
            get {
                return ResourceManager.GetString("Plans_Title_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informacion Comex.
        /// </summary>
        public static string Plans_Title_Information {
            get {
                return ResourceManager.GetString("Plans_Title_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Módulos.
        /// </summary>
        public static string Plans_Title_Modules {
            get {
                return ResourceManager.GetString("Plans_Title_Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planes.
        /// </summary>
        public static string Plans_Title_Plans {
            get {
                return ResourceManager.GetString("Plans_Title_Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string Plans_Title_Price {
            get {
                return ResourceManager.GetString("Plans_Title_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string Plans_Title_Users {
            get {
                return ResourceManager.GetString("Plans_Title_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen del plan.
        /// </summary>
        public static string PlanSummary_Text {
            get {
                return ResourceManager.GetString("PlanSummary_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publicado el.
        /// </summary>
        public static string Post_Publish {
            get {
                return ResourceManager.GetString("Post_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algo salío mal, inténtalo de nuevo más tarde.
        /// </summary>
        public static string Request_Error_Message {
            get {
                return ResourceManager.GetString("Request_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Request_Error_Title {
            get {
                return ResourceManager.GetString("Request_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su solicitud está siendo procesada y nos contactaremos a la brevedad con usted..
        /// </summary>
        public static string Request_Message {
            get {
                return ResourceManager.GetString("Request_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Contacto o Soporte.
        /// </summary>
        public static string Request_Text01 {
            get {
                return ResourceManager.GetString("Request_Text01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Cotización.
        /// </summary>
        public static string Request_Text02 {
            get {
                return ResourceManager.GetString("Request_Text02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Muchas gracias por su interés!.
        /// </summary>
        public static string Request_Title {
            get {
                return ResourceManager.GetString("Request_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a es obligatorio.
        /// </summary>
        public static string Required_Text {
            get {
                return ResourceManager.GetString("Required_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su usuario ya alcanzó el máximo contratado de ingresos al mes..
        /// </summary>
        public static string rpta4 {
            get {
                return ResourceManager.GetString("rpta4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SINPROGRAMA.
        /// </summary>
        public static string rpta5 {
            get {
                return ResourceManager.GetString("rpta5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, el ingreso desde esta máquina excede a la cantidad contratada..
        /// </summary>
        public static string rpta6 {
            get {
                return ResourceManager.GetString("rpta6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Search_Button {
            get {
                return ResourceManager.GetString("Search_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usted desea ver las.
        /// </summary>
        public static string Search_Form_Item01 {
            get {
                return ResourceManager.GetString("Search_Form_Item01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        public static string Search_Form_Item02 {
            get {
                return ResourceManager.GetString("Search_Form_Item02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Comercial.
        /// </summary>
        public static string Search_Form_Item03 {
            get {
                return ResourceManager.GetString("Search_Form_Item03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida.
        /// </summary>
        public static string Search_Form_Item04 {
            get {
                return ResourceManager.GetString("Search_Form_Item04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importador.
        /// </summary>
        public static string Search_Form_Item05 {
            get {
                return ResourceManager.GetString("Search_Form_Item05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportador.
        /// </summary>
        public static string Search_Form_Item06 {
            get {
                return ResourceManager.GetString("Search_Form_Item06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros.
        /// </summary>
        public static string Search_Form_Item07 {
            get {
                return ResourceManager.GetString("Search_Form_Item07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información en línea desde 01-ENE.-2012 hasta 30-ABR.-2017.
        /// </summary>
        public static string Search_Form_Item08 {
            get {
                return ResourceManager.GetString("Search_Form_Item08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        public static string Search_Form_Item09 {
            get {
                return ResourceManager.GetString("Search_Form_Item09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hasta.
        /// </summary>
        public static string Search_Form_Item10 {
            get {
                return ResourceManager.GetString("Search_Form_Item10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En la prueba gratuita solo se muestran 03 meses de información.
        /// </summary>
        public static string Search_Form_Item11 {
            get {
                return ResourceManager.GetString("Search_Form_Item11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer Buscador.
        /// </summary>
        public static string Search_ResetButton {
            get {
                return ResourceManager.GetString("Search_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar &gt;.
        /// </summary>
        public static string Send_Button {
            get {
                return ResourceManager.GetString("Send_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para.
        /// </summary>
        public static string Service_Text_Title_For {
            get {
                return ResourceManager.GetString("Service_Text_Title_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección de Facturación 1.
        /// </summary>
        public static string Stripe_Form_BillingAddress {
            get {
                return ResourceManager.GetString("Stripe_Form_BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección de Facturación 2.
        /// </summary>
        public static string Stripe_Form_BillingAddress2 {
            get {
                return ResourceManager.GetString("Stripe_Form_BillingAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad de Facturación.
        /// </summary>
        public static string Stripe_Form_BillingCity {
            get {
                return ResourceManager.GetString("Stripe_Form_BillingCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País de Facturación.
        /// </summary>
        public static string Stripe_Form_BillingCountry {
            get {
                return ResourceManager.GetString("Stripe_Form_BillingCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Facturación.
        /// </summary>
        public static string Stripe_Form_BillingState {
            get {
                return ResourceManager.GetString("Stripe_Form_BillingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titular de la tarjeta.
        /// </summary>
        public static string Stripe_Form_CardName {
            get {
                return ResourceManager.GetString("Stripe_Form_CardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de tarjeta.
        /// </summary>
        public static string Stripe_Form_CardNumber {
            get {
                return ResourceManager.GetString("Stripe_Form_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo de Seguridad.
        /// </summary>
        public static string Stripe_Form_Cvc {
            get {
                return ResourceManager.GetString("Stripe_Form_Cvc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección de Correo Electrónico.
        /// </summary>
        public static string Stripe_Form_Email {
            get {
                return ResourceManager.GetString("Stripe_Form_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Expiracion (MM/YY).
        /// </summary>
        public static string Stripe_Form_Expiry {
            get {
                return ResourceManager.GetString("Stripe_Form_Expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Teléfono.
        /// </summary>
        public static string Stripe_Form_Phone {
            get {
                return ResourceManager.GetString("Stripe_Form_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Postal.
        /// </summary>
        public static string Stripe_Form_Zip {
            get {
                return ResourceManager.GetString("Stripe_Form_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario y/o Contraseña incorrectos.
        /// </summary>
        public static string Success_title1 {
            get {
                return ResourceManager.GetString("Success_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario inactivo.
        /// </summary>
        public static string Success_title2 {
            get {
                return ResourceManager.GetString("Success_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Acceso no autorizado!.
        /// </summary>
        public static string Success_title3 {
            get {
                return ResourceManager.GetString("Success_title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡No se pudo ingresar al sistema!.
        /// </summary>
        public static string Success_title4 {
            get {
                return ResourceManager.GetString("Success_title4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Términos de Venta.
        /// </summary>
        public static string Terminos_Venta_Link {
            get {
                return ResourceManager.GetString("Terminos_Venta_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condiciones de Venta.
        /// </summary>
        public static string Terminos_Venta_Titulo {
            get {
                return ResourceManager.GetString("Terminos_Venta_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba Gratis.
        /// </summary>
        public static string TrialText {
            get {
                return ResourceManager.GetString("TrialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de tarjeta.
        /// </summary>
        public static string TypeCard_Text {
            get {
                return ResourceManager.GetString("TypeCard_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver detalles del plan.
        /// </summary>
        public static string ViewFeatures_Text {
            get {
                return ResourceManager.GetString("ViewFeatures_Text", resourceCulture);
            }
        }
    }
}
