//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AdminResources", typeof(AdminResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Alertas.
        /// </summary>
        public static string Add_Alerts {
            get {
                return ResourceManager.GetString("Add_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string Add_Text {
            get {
                return ResourceManager.GetString("Add_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a Mis Marcas.
        /// </summary>
        public static string Add_ToMyBrands_Button {
            get {
                return ResourceManager.GetString("Add_ToMyBrands_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a Mis Exportadores.
        /// </summary>
        public static string Add_ToMyExporters_Button {
            get {
                return ResourceManager.GetString("Add_ToMyExporters_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a Mis Importadores.
        /// </summary>
        public static string Add_ToMyImporters_Button {
            get {
                return ResourceManager.GetString("Add_ToMyImporters_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a Mis Productos.
        /// </summary>
        public static string Add_ToMyProducts_Button {
            get {
                return ResourceManager.GetString("Add_ToMyProducts_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a Grupo.
        /// </summary>
        public static string AddToGroup_Text {
            get {
                return ResourceManager.GetString("AddToGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a Mis Alertas.
        /// </summary>
        public static string AddToGroup_Text_To_Alerta {
            get {
                return ResourceManager.GetString("AddToGroup_Text_To_Alerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Aduana Destino.
        /// </summary>
        public static string AduanaDestinationInfoComplementaria_text {
            get {
                return ResourceManager.GetString("AduanaDestinationInfoComplementaria_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Aduana Origen.
        /// </summary>
        public static string AduanaOriginInfoComplementaria_text {
            get {
                return ResourceManager.GetString("AduanaOriginInfoComplementaria_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad máxima de alertas se excedió de acuerdo con su plan.
        /// </summary>
        public static string AlertExceed_Text {
            get {
                return ResourceManager.GetString("AlertExceed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alertas de.
        /// </summary>
        public static string AlertsOf_Text {
            get {
                return ResourceManager.GetString("AlertsOf_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analizar en.
        /// </summary>
        public static string AnalyzeIn_Text {
            get {
                return ResourceManager.GetString("AnalyzeIn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking Marca.
        /// </summary>
        public static string BrandSummary_Text {
            get {
                return ResourceManager.GetString("BrandSummary_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Alertas.
        /// </summary>
        public static string btnAddAlert_Text {
            get {
                return ResourceManager.GetString("btnAddAlert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Usuario.
        /// </summary>
        public static string BtnNewUser_Text {
            get {
                return ResourceManager.GetString("BtnNewUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Alerta.
        /// </summary>
        public static string BtnSetAlert_Text {
            get {
                return ResourceManager.GetString("BtnSetAlert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Detalle.
        /// </summary>
        public static string ButtonDetails_Text {
            get {
                return ResourceManager.GetString("ButtonDetails_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel_Text {
            get {
                return ResourceManager.GetString("Cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temas.
        /// </summary>
        public static string ChartThemes_Text {
            get {
                return ResourceManager.GetString("ChartThemes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc. Comercial.
        /// </summary>
        public static string ComercialDesc_FilterText {
            get {
                return ResourceManager.GetString("ComercialDesc_FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción Comercial.
        /// </summary>
        public static string Commercial_Description_Text {
            get {
                return ResourceManager.GetString("Commercial_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción Comercial.
        /// </summary>
        public static string CommercialDescription_FormField_Label {
            get {
                return ResourceManager.GetString("CommercialDescription_FormField_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañía.
        /// </summary>
        public static string Company_Text {
            get {
                return ResourceManager.GetString("Company_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañias.
        /// </summary>
        public static string Company_Text_02 {
            get {
                return ResourceManager.GetString("Company_Text_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Nuevo Grupo.
        /// </summary>
        public static string CreateNewGroup_Text {
            get {
                return ResourceManager.GetString("CreateNewGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aduana.
        /// </summary>
        public static string Customs_FilterText {
            get {
                return ResourceManager.GetString("Customs_FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aduana DUA.
        /// </summary>
        public static string CustomsDUA_FilterText {
            get {
                return ResourceManager.GetString("CustomsDUA_FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Alertas.
        /// </summary>
        public static string Delete_ToMyAlerts_Button {
            get {
                return ResourceManager.GetString("Delete_ToMyAlerts_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En esta sección Ud. podrá editar, eliminar y cambiar sus Alertas, juntando a varios  de ellos (productos con compañías) según su criterio..
        /// </summary>
        public static string Description_AlertsFavorites_Text {
            get {
                return ResourceManager.GetString("Description_AlertsFavorites_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condiciones: Para poder crear una alerta, previamente deberá haber agregado un producto o compañias a sus favoritos. Las Alertas llegarán a su correo cada vez que se actualice la información del pais donde haya creado la alerta..
        /// </summary>
        public static string Description_AlertsFavorites2_Text {
            get {
                return ResourceManager.GetString("Description_AlertsFavorites2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Alertas:.
        /// </summary>
        public static string Description_AlertsFavorites3_Text {
            get {
                return ResourceManager.GetString("Description_AlertsFavorites3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking Países Destino.
        /// </summary>
        public static string DestinationCountriesSummary_Text {
            get {
                return ResourceManager.GetString("DestinationCountriesSummary_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País Destino.
        /// </summary>
        public static string DestinationCountry_FormField_Label {
            get {
                return ResourceManager.GetString("DestinationCountry_FormField_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto Destino.
        /// </summary>
        public static string DestinationPort_FilterText {
            get {
                return ResourceManager.GetString("DestinationPort_FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino.
        /// </summary>
        public static string DestinationText {
            get {
                return ResourceManager.GetString("DestinationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string DetailButton_Text {
            get {
                return ResourceManager.GetString("DetailButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ud no tiene Empresas favoritas.
        /// </summary>
        public static string DoNotFavoriteCompanies_Text {
            get {
                return ResourceManager.GetString("DoNotFavoriteCompanies_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ud no tiene Productos favoritos.
        /// </summary>
        public static string DoNotFavoriteProducts_Text {
            get {
                return ResourceManager.GetString("DoNotFavoriteProducts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron exportaciones.
        /// </summary>
        public static string DoNotFoundExports_Text {
            get {
                return ResourceManager.GetString("DoNotFoundExports_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron importaciones.
        /// </summary>
        public static string DoNotFoundImports_Text {
            get {
                return ResourceManager.GetString("DoNotFoundImports_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar a PDF.
        /// </summary>
        public static string DownloadPDF_Text {
            get {
                return ResourceManager.GetString("DownloadPDF_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar a PNG.
        /// </summary>
        public static string DownloadPNG_Text {
            get {
                return ResourceManager.GetString("DownloadPNG_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si lo desea puede descargar los registros a un archivo Excel.
        /// </summary>
        public static string DownloadResultsToExcel_Text {
            get {
                return ResourceManager.GetString("DownloadResultsToExcel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar Archivo.
        /// </summary>
        public static string DownloadToExcel_Text {
            get {
                return ResourceManager.GetString("DownloadToExcel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País Embarque.
        /// </summary>
        public static string EmbarqueCountry_FormField_Label {
            get {
                return ResourceManager.GetString("EmbarqueCountry_FormField_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La alerta ya existe.
        /// </summary>
        public static string ExistsAlert_Text {
            get {
                return ResourceManager.GetString("ExistsAlert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad &lt;br&gt; Exportada.
        /// </summary>
        public static string ExportedQuanty_Text {
            get {
                return ResourceManager.GetString("ExportedQuanty_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking Exportadores.
        /// </summary>
        public static string ExportersSummary_Text {
            get {
                return ResourceManager.GetString("ExportersSummary_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones para exportar.
        /// </summary>
        public static string ExportMenuButtonTitle_Text {
            get {
                return ResourceManager.GetString("ExportMenuButtonTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportaciones.
        /// </summary>
        public static string Exports_Text {
            get {
                return ResourceManager.GetString("Exports_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar Tabla a Excel.
        /// </summary>
        public static string ExportTableToExcel_Text {
            get {
                return ResourceManager.GetString("ExportTableToExcel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorito.
        /// </summary>
        public static string Favorite_Text {
            get {
                return ResourceManager.GetString("Favorite_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Favorito.
        /// </summary>
        public static string FavoriteName_Text {
            get {
                return ResourceManager.GetString("FavoriteName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoritos.
        /// </summary>
        public static string Favorites_Word {
            get {
                return ResourceManager.GetString("Favorites_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Marcas.
        /// </summary>
        public static string Filter_MyBrands_Button {
            get {
                return ResourceManager.GetString("Filter_MyBrands_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Compañias.
        /// </summary>
        public static string Filter_MyCompanies_Text {
            get {
                return ResourceManager.GetString("Filter_MyCompanies_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Exportadores.
        /// </summary>
        public static string Filter_MyExporters_Button {
            get {
                return ResourceManager.GetString("Filter_MyExporters_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Importadores.
        /// </summary>
        public static string Filter_MyImporters_Button {
            get {
                return ResourceManager.GetString("Filter_MyImporters_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Productos.
        /// </summary>
        public static string Filter_MyProducts_Button {
            get {
                return ResourceManager.GetString("Filter_MyProducts_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aduana.
        /// </summary>
        public static string FilterText_Aduana {
            get {
                return ResourceManager.GetString("FilterText_Aduana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distrito.
        /// </summary>
        public static string FilterText_District {
            get {
                return ResourceManager.GetString("FilterText_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vía Transporte.
        /// </summary>
        public static string FilterText_ViaTransp {
            get {
                return ResourceManager.GetString("FilterText_ViaTransp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string From_Text {
            get {
                return ResourceManager.GetString("From_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partida.
        /// </summary>
        public static string HTS_Code_Text {
            get {
                return ResourceManager.GetString("HTS_Code_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción Partida Aduanera.
        /// </summary>
        public static string HTS_CodeDescription_Text {
            get {
                return ResourceManager.GetString("HTS_CodeDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción Partida.
        /// </summary>
        public static string HTS_Description_Text {
            get {
                return ResourceManager.GetString("HTS_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad &lt;br&gt; Importada.
        /// </summary>
        public static string ImportedQuanty_Text {
            get {
                return ResourceManager.GetString("ImportedQuanty_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking Importadores.
        /// </summary>
        public static string ImportersSummary_Text {
            get {
                return ResourceManager.GetString("ImportersSummary_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importaciones.
        /// </summary>
        public static string Imports_Text {
            get {
                return ResourceManager.GetString("Imports_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información de este tab proviene directamente de la aduana del país de origen, la cual tiene más información a detalle que puede ayudar a un mejor análisis de la partida. Recomendamos utilizar esta información como complementaria..
        /// </summary>
        public static string InfoTabla_Details1 {
            get {
                return ResourceManager.GetString("InfoTabla_Details1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información de este tab proviene directamente de la aduana del país de destino, la cual tiene más información a detalle que puede ayudar a un mejor análisis de la partida. Recomendamos utilizar esta información como complementaria..
        /// </summary>
        public static string InfoTabla_Details2 {
            get {
                return ResourceManager.GetString("InfoTabla_Details2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información proviene directamente de la aduana de.
        /// </summary>
        public static string InfoTabla_Modal1 {
            get {
                return ResourceManager.GetString("InfoTabla_Modal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , la cual tiene más información a detalle que puede ayudar a un mejor análisis de la partida. Recomendamos utilizar esta información como complementaria..
        /// </summary>
        public static string InfoTabla_Modal2 {
            get {
                return ResourceManager.GetString("InfoTabla_Modal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Filtros.
        /// </summary>
        public static string Label_MyFilters {
            get {
                return ResourceManager.GetString("Label_MyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string LabelActive_Text {
            get {
                return ResourceManager.GetString("LabelActive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe.
        /// </summary>
        public static string LabelAmount_Text {
            get {
                return ResourceManager.GetString("LabelAmount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string LabelCompany_Text {
            get {
                return ResourceManager.GetString("LabelCompany_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuente.
        /// </summary>
        public static string LabelComplementaryInformation_Text {
            get {
                return ResourceManager.GetString("LabelComplementaryInformation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Creación.
        /// </summary>
        public static string LabelCreationDate_Text {
            get {
                return ResourceManager.GetString("LabelCreationDate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Fin.
        /// </summary>
        public static string LabelEndDate_Text {
            get {
                return ResourceManager.GetString("LabelEndDate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        public static string LabelInactive_Text {
            get {
                return ResourceManager.GetString("LabelInactive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string LabelMain_Text {
            get {
                return ResourceManager.GetString("LabelMain_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombres.
        /// </summary>
        public static string LabelNames_Text {
            get {
                return ResourceManager.GetString("LabelNames_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string LabelPassword_Text {
            get {
                return ResourceManager.GetString("LabelPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string LabelPhone_Text {
            get {
                return ResourceManager.GetString("LabelPhone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secundario.
        /// </summary>
        public static string LabelSecondary_Text {
            get {
                return ResourceManager.GetString("LabelSecondary_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicio.
        /// </summary>
        public static string LabelStartDate_Text {
            get {
                return ResourceManager.GetString("LabelStartDate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string LabelState_Text {
            get {
                return ResourceManager.GetString("LabelState_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string LabelSurname_Text {
            get {
                return ResourceManager.GetString("LabelSurname_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string LabelUser_Text {
            get {
                return ResourceManager.GetString("LabelUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Plan.
        /// </summary>
        public static string LabelUserPlan_Text {
            get {
                return ResourceManager.GetString("LabelUserPlan_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Usuario.
        /// </summary>
        public static string LabelUserType_Text {
            get {
                return ResourceManager.GetString("LabelUserType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último País Embarque.
        /// </summary>
        public static string LastShipmentCountry_FilterText {
            get {
                return ResourceManager.GetString("LastShipmentCountry_FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último Puerto Embarque.
        /// </summary>
        public static string LastShipmentPort_FilterText {
            get {
                return ResourceManager.GetString("LastShipmentPort_FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprar online.
        /// </summary>
        public static string LayoutBar_BuyButton {
            get {
                return ResourceManager.GetString("LayoutBar_BuyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALIR PRUEBA G..
        /// </summary>
        public static string LayoutBar_ExitModeFreeButton {
            get {
                return ResourceManager.GetString("LayoutBar_ExitModeFreeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LayoutBar_LanguageButton {
            get {
                return ResourceManager.GetString("LayoutBar_LanguageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido (a).
        /// </summary>
        public static string LayoutBar_Message {
            get {
                return ResourceManager.GetString("LayoutBar_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRUEBA GRATIS.
        /// </summary>
        public static string LayoutBar_ModeFreeButton {
            get {
                return ResourceManager.GetString("LayoutBar_ModeFreeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Cuenta.
        /// </summary>
        public static string LayoutMenu_Item01 {
            get {
                return ResourceManager.GetString("LayoutMenu_Item01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesión.
        /// </summary>
        public static string LayoutMenu_Item02 {
            get {
                return ResourceManager.GetString("LayoutMenu_Item02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Favoritos.
        /// </summary>
        public static string LayoutMenu_Item03 {
            get {
                return ResourceManager.GetString("LayoutMenu_Item03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Grupos.
        /// </summary>
        public static string LayoutMenu_Item04 {
            get {
                return ResourceManager.GetString("LayoutMenu_Item04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Alertas.
        /// </summary>
        public static string LayoutMenu_Item05 {
            get {
                return ResourceManager.GetString("LayoutMenu_Item05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Prueba Gratuita.
        /// </summary>
        public static string LayoutMenu_ModeFree {
            get {
                return ResourceManager.GetString("LayoutMenu_ModeFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Cuenta.
        /// </summary>
        public static string LayoutMenu_MyAccount {
            get {
                return ResourceManager.GetString("LayoutMenu_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifiesto.
        /// </summary>
        public static string Manifest_FilterText {
            get {
                return ResourceManager.GetString("Manifest_FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe agregar a mis exportadores para poder registrar la alerta..
        /// </summary>
        public static string MesExistsAlertEx_Text {
            get {
                return ResourceManager.GetString("MesExistsAlertEx_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe agregar a mis importadores para poder registrar la alerta..
        /// </summary>
        public static string MesExistsAlertIm_Text {
            get {
                return ResourceManager.GetString("MesExistsAlertIm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe agregar a mis productos para poder registrar la alerta..
        /// </summary>
        public static string MesExistsAlertPr_Text {
            get {
                return ResourceManager.GetString("MesExistsAlertPr_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Su plan sólo permite seleccionar.
        /// </summary>
        public static string Message_Alerts_Max_Selected_01 {
            get {
                return ResourceManager.GetString("Message_Alerts_Max_Selected_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superaste el máximo de seleccionados.
        /// </summary>
        public static string Message_Alerts_Max_Selected_02 {
            get {
                return ResourceManager.GetString("Message_Alerts_Max_Selected_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superó el máximo de empresas seleccionadas.
        /// </summary>
        public static string Message_Alerts_Max_Selected_03 {
            get {
                return ResourceManager.GetString("Message_Alerts_Max_Selected_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superó el máximo de productos seleccionados.
        /// </summary>
        public static string Message_Alerts_Max_Selected_04 {
            get {
                return ResourceManager.GetString("Message_Alerts_Max_Selected_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione al menos un detalle de favorito.
        /// </summary>
        public static string Message_Alerts_Not_Detail_Selected {
            get {
                return ResourceManager.GetString("Message_Alerts_Not_Detail_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione al menos un favorito.
        /// </summary>
        public static string Message_Alerts_Not_Selected {
            get {
                return ResourceManager.GetString("Message_Alerts_Not_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminado con éxito.
        /// </summary>
        public static string Message_Alerts_Succes_Deleted {
            get {
                return ResourceManager.GetString("Message_Alerts_Succes_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grabado con éxito.
        /// </summary>
        public static string Message_Alerts_Succes_Saved {
            get {
                return ResourceManager.GetString("Message_Alerts_Succes_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregó el favorito seleccionado..
        /// </summary>
        public static string Message_FavoriteAdded {
            get {
                return ResourceManager.GetString("Message_FavoriteAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El favorito seleccionado ya existe.
        /// </summary>
        public static string Message_FavoriteExists {
            get {
                return ResourceManager.GetString("Message_FavoriteExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede agregar el favorito seleccionado.
        /// </summary>
        public static string Message_FavoriteNotAdded {
            get {
                return ResourceManager.GetString("Message_FavoriteNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregaron los favoritos seleccionados..
        /// </summary>
        public static string Message_FavoritesAdded {
            get {
                return ResourceManager.GetString("Message_FavoritesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoritos seleccionados ya existen.
        /// </summary>
        public static string Message_FavoritesExists {
            get {
                return ResourceManager.GetString("Message_FavoritesExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se agregaron algunos favoritos seleccionados..
        /// </summary>
        public static string Message_SomeoneFavoritesAdded {
            get {
                return ResourceManager.GetString("Message_SomeoneFavoritesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor seleccione el(los) elemento(s) a Agregar.
        /// </summary>
        public static string Message_Valida_AddFilterSearchButton {
            get {
                return ResourceManager.GetString("Message_Valida_AddFilterSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor seleccione una Compañia.
        /// </summary>
        public static string Message_Validate_SelectCompanie_Text {
            get {
                return ResourceManager.GetString("Message_Validate_SelectCompanie_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor seleccione un Producto.
        /// </summary>
        public static string Message_Validate_SelectProduct_Text {
            get {
                return ResourceManager.GetString("Message_Validate_SelectProduct_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede agregar los favoritos seleccionados porque superará el límite de su plan contratado.
        /// </summary>
        public static string MessageLimitPlanFavorites {
            get {
                return ResourceManager.GetString("MessageLimitPlanFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde Agosto 2016 la aduana de Chile eliminó las columnas del nombre de las empresas y el RUT de importadores y exportadores de Chile. Ante esta situación y con acciones de machine learning y minería de datos a través de nuestro servicio de.
        /// </summary>
        public static string MessageModalAduanaCL_Text {
            get {
                return ResourceManager.GetString("MessageModalAduanaCL_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to podemos predecir con una probabilidad bastante certera la información de estas columnas ocultas por la aduana. Pedimos utilizar la información de estas columnas como complementaria.
        /// </summary>
        public static string MessageModalAduanaCL2_Text {
            get {
                return ResourceManager.GetString("MessageModalAduanaCL2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atentamente,.
        /// </summary>
        public static string Modal_VentanaAviso_Att {
            get {
                return ResourceManager.GetString("Modal_VentanaAviso_Att", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contáctenos.
        /// </summary>
        public static string Modal_VentanaAviso_Contactus_Button {
            get {
                return ResourceManager.GetString("Modal_VentanaAviso_Contactus_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimados Amigos,.
        /// </summary>
        public static string Modal_VentanaAviso_Greeting {
            get {
                return ResourceManager.GetString("Modal_VentanaAviso_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si deseas adquirir los planes que tienen esta nueva base de datos.
        /// </summary>
        public static string Modal_VentanaAviso_InvitationNewDatabase {
            get {
                return ResourceManager.GetString("Modal_VentanaAviso_InvitationNewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queremos comunicarles que a partir de ahora Veritrade cuenta con información de México Vía marítima en detalle.  Para acceder a esta información, tienes que escoger la Región: Latinoamerica y después escoger &quot;México Detalle Marítimo&quot;:.
        /// </summary>
        public static string Modal_VentanaAviso_Message1 {
            get {
                return ResourceManager.GetString("Modal_VentanaAviso_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta información ya se encuentra disponible para nuestros clientes de los Planes Full Latam y Latam Full World.
        ///														&lt;br&gt;Como siempre nuestro objetivo es mejorar la usabilidad, experiencia de uso y la calidad de nuestras bases de datos para el beneficio de nuestros clientes..
        /// </summary>
        public static string Modal_VentanaAviso_Message2 {
            get {
                return ResourceManager.GetString("Modal_VentanaAviso_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡ Nueva  Base de Datos: México Vía marítima en detalle !.
        /// </summary>
        public static string Modal_VentanaAviso_NewDatabase {
            get {
                return ResourceManager.GetString("Modal_VentanaAviso_NewDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Equipo Veritrade.
        /// </summary>
        public static string Modal_VentanaAviso_Sign {
            get {
                return ResourceManager.GetString("Modal_VentanaAviso_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu aliado en información de comercio exterior de Latinoamérica y el mundo.
        /// </summary>
        public static string Modal_VentanaAviso_Slogan {
            get {
                return ResourceManager.GetString("Modal_VentanaAviso_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novedades Veritrade.
        /// </summary>
        public static string Modal_VentanaAviso_VeritradeNews {
            get {
                return ResourceManager.GetString("Modal_VentanaAviso_VeritradeNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string Modal_VentanaContactenos_SendButton {
            get {
                return ResourceManager.GetString("Modal_VentanaContactenos_SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de contacto o soporte.
        /// </summary>
        public static string Modal_VentanaContactenos_Title {
            get {
                return ResourceManager.GetString("Modal_VentanaContactenos_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contáctenos.
        /// </summary>
        public static string Modal_VentanaMensaje_LnkContactenos {
            get {
                return ResourceManager.GetString("Modal_VentanaMensaje_LnkContactenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si desea mas información.
        /// </summary>
        public static string Modal_VentanaMensaje_MessageContactenos {
            get {
                return ResourceManager.GetString("Modal_VentanaMensaje_MessageContactenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sesión ha expirado.
        /// </summary>
        public static string Modal_VentanaSesion_Message {
            get {
                return ResourceManager.GetString("Modal_VentanaSesion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesión Expirada.
        /// </summary>
        public static string Modal_VentanaSesion_Title {
            get {
                return ResourceManager.GetString("Modal_VentanaSesion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No volver a mostrar.
        /// </summary>
        public static string Modal_VentanaVideo_Button_No_Show {
            get {
                return ResourceManager.GetString("Modal_VentanaVideo_Button_No_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queremos ayudarte a maximizar el uso que puedas darle a Veritrade. Por eso te brindamos estos tutoriales que te ayudarán a ti y a tu empresa a obtener toda la información que necesitas cuando la necesitas..
        /// </summary>
        public static string Modal_VentanaVideo_Message {
            get {
                return ResourceManager.GetString("Modal_VentanaVideo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puedes volver a ver los videos haciendo clic en &quot;Ver video tutorial&quot; ubicado en la barra superior.
        /// </summary>
        public static string Modal_VentanaVideo_Text_No_Show {
            get {
                return ResourceManager.GetString("Modal_VentanaVideo_Text_No_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cómo buscar en Veritrade.
        /// </summary>
        public static string Modal_VentanaVideo_Title {
            get {
                return ResourceManager.GetString("Modal_VentanaVideo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/embed/dw0qgNuIePQ?rel=0.
        /// </summary>
        public static string Modal_VentanaVideo_UrlVideo {
            get {
                return ResourceManager.GetString("Modal_VentanaVideo_UrlVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string Modal_VentanContactenos_FormLabelMessage {
            get {
                return ResourceManager.GetString("Modal_VentanContactenos_FormLabelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACEPTAR.
        /// </summary>
        public static string Modal_VentanMensaje_OKButton {
            get {
                return ResourceManager.GetString("Modal_VentanMensaje_OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el Nuevo Grupo.
        /// </summary>
        public static string ModalAgregarFavoritos_MsjValidateEnterNewGroup {
            get {
                return ResourceManager.GetString("ModalAgregarFavoritos_MsjValidateEnterNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor seleccione al menos alguna opción.
        /// </summary>
        public static string ModalAgregarFavoritos_MsjValidateSelectedOption {
            get {
                return ResourceManager.GetString("ModalAgregarFavoritos_MsjValidateSelectedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si tiene alguna consulta o desea migrar de plan:.
        /// </summary>
        public static string ModalMessageFree_LinkContactenos {
            get {
                return ResourceManager.GetString("ModalMessageFree_LinkContactenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted está en una prueba gratuita, donde podrá apreciar todas las Bases de datos que cuenta en Veritrade. Tome en cuenta que esta opción es de carácter informativo y solo tendrá disponible 3 meses información..
        /// </summary>
        public static string ModalMessageFree_Message {
            get {
                return ResourceManager.GetString("ModalMessageFree_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prueba Gratuita.
        /// </summary>
        public static string ModalMessageFree_Title {
            get {
                return ResourceManager.GetString("ModalMessageFree_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        public static string Model_FormField_Label {
            get {
                return ResourceManager.GetString("Model_FormField_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar al menos una palabra de 3 letras.
        /// </summary>
        public static string More_Size_Word {
            get {
                return ResourceManager.GetString("More_Size_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es un correo electrónico válido.
        /// </summary>
        public static string My_Acc_Valid_Email {
            get {
                return ResourceManager.GetString("My_Acc_Valid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige una Compañía.
        /// </summary>
        public static string My_Alerts_Choise_Comp {
            get {
                return ResourceManager.GetString("My_Alerts_Choise_Comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige un Producto.
        /// </summary>
        public static string My_Alerts_Choise_Prod {
            get {
                return ResourceManager.GetString("My_Alerts_Choise_Prod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previo del correo Alerta.
        /// </summary>
        public static string My_Alerts_Preview {
            get {
                return ResourceManager.GetString("My_Alerts_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Tutorial.
        /// </summary>
        public static string MySearchs_VideoTutorial_Text {
            get {
                return ResourceManager.GetString("MySearchs_VideoTutorial_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partida.
        /// </summary>
        public static string Nandina2_FilterText {
            get {
                return ResourceManager.GetString("Nandina2_FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshabilitar Alertas.
        /// </summary>
        public static string NavBar_DisAlert {
            get {
                return ResourceManager.GetString("NavBar_DisAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar Alertas.
        /// </summary>
        public static string NavBar_EnAlert {
            get {
                return ResourceManager.GetString("NavBar_EnAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Búsquedas.
        /// </summary>
        public static string NavBar_Item01 {
            get {
                return ResourceManager.GetString("NavBar_Item01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Productos.
        /// </summary>
        public static string NavBar_Item02 {
            get {
                return ResourceManager.GetString("NavBar_Item02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Compañías.
        /// </summary>
        public static string NavBar_Item03 {
            get {
                return ResourceManager.GetString("NavBar_Item03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Productos - Compañías.
        /// </summary>
        public static string NavBar_Item04 {
            get {
                return ResourceManager.GetString("NavBar_Item04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Compañías - Productos.
        /// </summary>
        public static string NavBar_Item05 {
            get {
                return ResourceManager.GetString("NavBar_Item05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron registros.
        /// </summary>
        public static string NoRecordsFound_Text {
            get {
                return ResourceManager.GetString("NoRecordsFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota: .
        /// </summary>
        public static string Note_Label {
            get {
                return ResourceManager.GetString("Note_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificado.
        /// </summary>
        public static string Notified_FilterText {
            get {
                return ResourceManager.GetString("Notified_FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string Of_text {
            get {
                return ResourceManager.GetString("Of_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione.
        /// </summary>
        public static string OptionTextField_Select {
            get {
                return ResourceManager.GetString("OptionTextField_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking Países Origen.
        /// </summary>
        public static string OriginCountriesSummary_Text {
            get {
                return ResourceManager.GetString("OriginCountriesSummary_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País Origen.
        /// </summary>
        public static string OriginCountry_FormField_Label {
            get {
                return ResourceManager.GetString("OriginCountry_FormField_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen.
        /// </summary>
        public static string OriginText {
            get {
                return ResourceManager.GetString("OriginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período.
        /// </summary>
        public static string Period_Text {
            get {
                return ResourceManager.GetString("Period_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen Período.
        /// </summary>
        public static string PeriodSummary_Text {
            get {
                return ResourceManager.GetString("PeriodSummary_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir gráfico.
        /// </summary>
        public static string PrintChart_Text {
            get {
                return ResourceManager.GetString("PrintChart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        public static string Product_Text {
            get {
                return ResourceManager.GetString("Product_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string Product_Text_02 {
            get {
                return ResourceManager.GetString("Product_Text_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking Productos.
        /// </summary>
        public static string ProductsRanking_Text {
            get {
                return ResourceManager.GetString("ProductsRanking_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registro(s).
        /// </summary>
        public static string Records_Text {
            get {
                return ResourceManager.GetString("Records_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros.
        /// </summary>
        public static string RecordsFirsLetterUpperCase_Text {
            get {
                return ResourceManager.GetString("RecordsFirsLetterUpperCase_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se registró la alerta..
        /// </summary>
        public static string SaveAlert_Text {
            get {
                return ResourceManager.GetString("SaveAlert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione los elementos a Agregar.
        /// </summary>
        public static string SelectItemsAdd_Text {
            get {
                return ResourceManager.GetString("SelectItemsAdd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su plan no permite ver la información crediticia de esta empresa.
        /// </summary>
        public static string SentinelValidation_Text {
            get {
                return ResourceManager.GetString("SentinelValidation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Alerta.
        /// </summary>
        public static string Title_Alerts_01 {
            get {
                return ResourceManager.GetString("Title_Alerts_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alertas Creadas.
        /// </summary>
        public static string Title_Alerts_02 {
            get {
                return ResourceManager.GetString("Title_Alerts_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador de mis alertas.
        /// </summary>
        public static string TitleAlerts_Text {
            get {
                return ResourceManager.GetString("TitleAlerts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total registros.
        /// </summary>
        public static string Total_records_Text {
            get {
                return ResourceManager.GetString("Total_records_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total &lt;br&gt; Exportado.
        /// </summary>
        public static string TotalExported_Text {
            get {
                return ResourceManager.GetString("TotalExported_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total &lt;br&gt; Importado.
        /// </summary>
        public static string TotalImported_Text {
            get {
                return ResourceManager.GetString("TotalImported_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KILOGRAMOS.
        /// </summary>
        public static string TypeUNIT_Text {
            get {
                return ResourceManager.GetString("TypeUNIT_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilos.
        /// </summary>
        public static string TypeUNIT_Text_CN {
            get {
                return ResourceManager.GetString("TypeUNIT_Text_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US$.
        /// </summary>
        public static string TypeUSS_Text {
            get {
                return ResourceManager.GetString("TypeUSS_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad.
        /// </summary>
        public static string Unit_Text {
            get {
                return ResourceManager.GetString("Unit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio &lt;br&gt; Unitario.
        /// </summary>
        public static string UnitPrice_Text {
            get {
                return ResourceManager.GetString("UnitPrice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto Descarga.
        /// </summary>
        public static string UnloadingPort_FilterText {
            get {
                return ResourceManager.GetString("UnloadingPort_FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Alertas.
        /// </summary>
        public static string Update_ToMyAlerts_Button {
            get {
                return ResourceManager.GetString("Update_ToMyAlerts_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/embed/E3BwnnxJyhI?rel=0.
        /// </summary>
        public static string UrlVideo_MyCompanies {
            get {
                return ResourceManager.GetString("UrlVideo_MyCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/embed/VpQXJhZe7ZM?rel=0.
        /// </summary>
        public static string UrlVideo_MyProducts {
            get {
                return ResourceManager.GetString("UrlVideo_MyProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VeriAlertas.
        /// </summary>
        public static string VeriAlertas_Label {
            get {
                return ResourceManager.GetString("VeriAlertas_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VER GRÁFICOS.
        /// </summary>
        public static string ViewCharts_Button {
            get {
                return ResourceManager.GetString("ViewCharts_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Aranceles.
        /// </summary>
        public static string ViewTariffs_Button {
            get {
                return ResourceManager.GetString("ViewTariffs_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso Bruto.
        /// </summary>
        public static string Weight_Gross_Text {
            get {
                return ResourceManager.GetString("Weight_Gross_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso Neto.
        /// </summary>
        public static string WeightNet_Text {
            get {
                return ResourceManager.GetString("WeightNet_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienes.
        /// </summary>
        public static string YouHave_Text {
            get {
                return ResourceManager.GetString("YouHave_Text", resourceCulture);
            }
        }
    }
}
