//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MinisiteResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MinisiteResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MinisiteResources", typeof(MinisiteResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importaciones y Exportaciones.
        /// </summary>
        public static string Block01_Text01 {
            get {
                return ResourceManager.GetString("Block01_Text01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importaciones y Exportaciones de.
        /// </summary>
        public static string Block02_Text01 {
            get {
                return ResourceManager.GetString("Block02_Text01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de comercio exterior: precios, productos, clientes, competencia, proveedores y más.
        /// </summary>
        public static string Block02_Text02 {
            get {
                return ResourceManager.GetString("Block02_Text02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a registros en los últimos 5 años.
        /// </summary>
        public static string Block02_Text03 {
            get {
                return ResourceManager.GetString("Block02_Text03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comercio exterior en los últimos 5 años.
        /// </summary>
        public static string Block03_Text01 {
            get {
                return ResourceManager.GetString("Block03_Text01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No registra.
        /// </summary>
        public static string Block03_Text02 {
            get {
                return ResourceManager.GetString("Block03_Text02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para mayor informacion solicite una.
        /// </summary>
        public static string BlockImage_Text01 {
            get {
                return ResourceManager.GetString("BlockImage_Text01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a prueba gratuita.
        /// </summary>
        public static string BlockImage_Text02 {
            get {
                return ResourceManager.GetString("BlockImage_Text02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No registra exportaciones en este periodo.
        /// </summary>
        public static string Chart01_Empty {
            get {
                return ResourceManager.GetString("Chart01_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor FOB Exportado US$.
        /// </summary>
        public static string Chart01_Title {
            get {
                return ResourceManager.GetString("Chart01_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No registra importaciones en este periodo.
        /// </summary>
        public static string Chart02_Empty {
            get {
                return ResourceManager.GetString("Chart02_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor CIF Importado US$.
        /// </summary>
        public static string Chart02_Title {
            get {
                return ResourceManager.GetString("Chart02_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paises.
        /// </summary>
        public static string Country_Text {
            get {
                return ResourceManager.GetString("Country_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportaciones.
        /// </summary>
        public static string Exports_Text {
            get {
                return ResourceManager.GetString("Exports_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba Gratuita.
        /// </summary>
        public static string FreeTrial_Text {
            get {
                return ResourceManager.GetString("FreeTrial_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importaciones.
        /// </summary>
        public static string Imports_Text {
            get {
                return ResourceManager.GetString("Imports_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esto es sólo una muestra de lo que Veritrade puede ofrecer. Solicita una prueba gratis y conoce más.
        /// </summary>
        public static string Modal_Footer_Description {
            get {
                return ResourceManager.GetString("Modal_Footer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Te gustó lo que viste?.
        /// </summary>
        public static string Modal_Footer_Title {
            get {
                return ResourceManager.GetString("Modal_Footer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida Aduanera.
        /// </summary>
        public static string Modal01_Title {
            get {
                return ResourceManager.GetString("Modal01_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida Aduanera.
        /// </summary>
        public static string Modal02_Desc01 {
            get {
                return ResourceManager.GetString("Modal02_Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Partida Aduanera.
        /// </summary>
        public static string Modal02_Desc02 {
            get {
                return ResourceManager.GetString("Modal02_Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aduana.
        /// </summary>
        public static string Modal02_Desc03 {
            get {
                return ResourceManager.GetString("Modal02_Desc03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Importación (dd/mm/yyyy).
        /// </summary>
        public static string Modal02_Desc04 {
            get {
                return ResourceManager.GetString("Modal02_Desc04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Exportación (dd/mm/yyyy).
        /// </summary>
        public static string Modal02_Desc05 {
            get {
                return ResourceManager.GetString("Modal02_Desc05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Comercial.
        /// </summary>
        public static string Modal02_Desc06 {
            get {
                return ResourceManager.GetString("Modal02_Desc06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importador.
        /// </summary>
        public static string Modal02_Desc07 {
            get {
                return ResourceManager.GetString("Modal02_Desc07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportador.
        /// </summary>
        public static string Modal02_Desc08 {
            get {
                return ResourceManager.GetString("Modal02_Desc08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso Bruto KG.
        /// </summary>
        public static string Modal02_Table01_Header01 {
            get {
                return ResourceManager.GetString("Modal02_Table01_Header01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso Neto KG.
        /// </summary>
        public static string Modal02_Table01_Header02 {
            get {
                return ResourceManager.GetString("Modal02_Table01_Header02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string Modal02_Table01_Header03 {
            get {
                return ResourceManager.GetString("Modal02_Table01_Header03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad.
        /// </summary>
        public static string Modal02_Table01_Header04 {
            get {
                return ResourceManager.GetString("Modal02_Table01_Header04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País Origen.
        /// </summary>
        public static string Modal02_Table01_Header05 {
            get {
                return ResourceManager.GetString("Modal02_Table01_Header05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País Destino.
        /// </summary>
        public static string Modal02_Table01_Header05B {
            get {
                return ResourceManager.GetString("Modal02_Table01_Header05B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País Compra.
        /// </summary>
        public static string Modal02_Table01_Header06 {
            get {
                return ResourceManager.GetString("Modal02_Table01_Header06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerto Embarque.
        /// </summary>
        public static string Modal02_Table01_Header07 {
            get {
                return ResourceManager.GetString("Modal02_Table01_Header07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pruerto Destino.
        /// </summary>
        public static string Modal02_Table01_Header07B {
            get {
                return ResourceManager.GetString("Modal02_Table01_Header07B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Via.
        /// </summary>
        public static string Modal02_Table01_Header08 {
            get {
                return ResourceManager.GetString("Modal02_Table01_Header08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transporte.
        /// </summary>
        public static string Modal02_Table01_Header09 {
            get {
                return ResourceManager.GetString("Modal02_Table01_Header09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agente Aduanera.
        /// </summary>
        public static string Modal02_Table01_Header10 {
            get {
                return ResourceManager.GetString("Modal02_Table01_Header10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FLETE US$ TOTAL.
        /// </summary>
        public static string Modal02_Table02_Header01 {
            get {
                return ResourceManager.GetString("Modal02_Table02_Header01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FLETE US$ UNIT..
        /// </summary>
        public static string Modal02_Table02_Header02 {
            get {
                return ResourceManager.GetString("Modal02_Table02_Header02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGURO US$ TOTAL.
        /// </summary>
        public static string Modal02_Table02_Header03 {
            get {
                return ResourceManager.GetString("Modal02_Table02_Header03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGURO US$ UNIT..
        /// </summary>
        public static string Modal02_Table02_Header04 {
            get {
                return ResourceManager.GetString("Modal02_Table02_Header04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CIF + IMPUESTOS (IGV NO INCLUYE) US$ UNIT.
        /// </summary>
        public static string Modal02_Table02_Header05 {
            get {
                return ResourceManager.GetString("Modal02_Table02_Header05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de Embarque.
        /// </summary>
        public static string Modal02_Title {
            get {
                return ResourceManager.GetString("Modal02_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        public static string Products_Text {
            get {
                return ResourceManager.GetString("Products_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicite su prueba gratuita.
        /// </summary>
        public static string Publish_Button {
            get {
                return ResourceManager.GetString("Publish_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miles de empresas usan VERITRADE para buscar PROVEEDORES Y COMPETIDORES.
        /// </summary>
        public static string Publish_Title {
            get {
                return ResourceManager.GetString("Publish_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busca una empresa.
        /// </summary>
        public static string Search_Company {
            get {
                return ResourceManager.GetString("Search_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registros.
        /// </summary>
        public static string Shipments_Text {
            get {
                return ResourceManager.GetString("Shipments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu plataforma digital de comercio exterior de latinoamérica y el mundo.
        /// </summary>
        public static string Slogan_Text {
            get {
                return ResourceManager.GetString("Slogan_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No registra importaciones en este periodo.
        /// </summary>
        public static string Table_Empty {
            get {
                return ResourceManager.GetString("Table_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principales productos exportados del 2016.
        /// </summary>
        public static string Table01_Export_Title {
            get {
                return ResourceManager.GetString("Table01_Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principales productos importados del 2016.
        /// </summary>
        public static string Table01_Import_Title {
            get {
                return ResourceManager.GetString("Table01_Import_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principales paises de exportación del 2016.
        /// </summary>
        public static string Table02_Export_Title {
            get {
                return ResourceManager.GetString("Table02_Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principales paises de importación del 2016.
        /// </summary>
        public static string Table02_Import_Title {
            get {
                return ResourceManager.GetString("Table02_Import_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con Veritrade usted podrá ver los detalles de las operaciones al máximo nivel permitido por cada país, teniendo como resultado el siguiente.
        /// </summary>
        public static string Table03_Description {
            get {
                return ResourceManager.GetString("Table03_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Table03_Header01 {
            get {
                return ResourceManager.GetString("Table03_Header01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida Aduanera.
        /// </summary>
        public static string Table03_Header02 {
            get {
                return ResourceManager.GetString("Table03_Header02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportador.
        /// </summary>
        public static string Table03_Header03 {
            get {
                return ResourceManager.GetString("Table03_Header03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importador.
        /// </summary>
        public static string Table03_Header04 {
            get {
                return ResourceManager.GetString("Table03_Header04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KG. Neto.
        /// </summary>
        public static string Table03_Header05 {
            get {
                return ResourceManager.GetString("Table03_Header05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string Table03_Header06 {
            get {
                return ResourceManager.GetString("Table03_Header06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unid..
        /// </summary>
        public static string Table03_Header07 {
            get {
                return ResourceManager.GetString("Table03_Header07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a US$ Unid..
        /// </summary>
        public static string Table03_Header08 {
            get {
                return ResourceManager.GetString("Table03_Header08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DUA.
        /// </summary>
        public static string Table03_Header09 {
            get {
                return ResourceManager.GetString("Table03_Header09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País Origen.
        /// </summary>
        public static string Table03_Header10 {
            get {
                return ResourceManager.GetString("Table03_Header10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País Destino.
        /// </summary>
        public static string Table03_Header10B {
            get {
                return ResourceManager.GetString("Table03_Header10B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Comercial.
        /// </summary>
        public static string Table03_Header11 {
            get {
                return ResourceManager.GetString("Table03_Header11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de Embarque.
        /// </summary>
        public static string Table03_Title {
            get {
                return ResourceManager.GetString("Table03_Title", resourceCulture);
            }
        }
    }
}
