//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MiPerfil {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiPerfil() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MiPerfil", typeof(MiPerfil).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar nuevo.
        /// </summary>
        public static string Add_new_Text {
            get {
                return ResourceManager.GetString("Add_new_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar nueva Marca.
        /// </summary>
        public static string Add_newBrand_Text {
            get {
                return ResourceManager.GetString("Add_newBrand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar favoritos a Grupo.
        /// </summary>
        public static string AddFavoritesToGroup_Text {
            get {
                return ResourceManager.GetString("AddFavoritesToGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos disponibles.
        /// </summary>
        public static string AvailableFields_Text {
            get {
                return ResourceManager.GetString("AvailableFields_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar nuevo Producto.
        /// </summary>
        public static string Btn_AddNewProduct {
            get {
                return ResourceManager.GetString("Btn_AddNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar seleccionados a Grupo.
        /// </summary>
        public static string Btn_AddSelectionToAGroup {
            get {
                return ResourceManager.GetString("Btn_AddSelectionToAGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar al grupo.
        /// </summary>
        public static string Btn_AddToGroup {
            get {
                return ResourceManager.GetString("Btn_AddToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VOLVER AL INICIO.
        /// </summary>
        public static string Btn_BackHome {
            get {
                return ResourceManager.GetString("Btn_BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar seleccionados.
        /// </summary>
        public static string Btn_DeleteSelection {
            get {
                return ResourceManager.GetString("Btn_DeleteSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a Mis Grupos.
        /// </summary>
        public static string Btn_GoToMyGroups {
            get {
                return ResourceManager.GetString("Btn_GoToMyGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Grupos Marcas.
        /// </summary>
        public static string Btn_MyBrandsGroups {
            get {
                return ResourceManager.GetString("Btn_MyBrandsGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Grupos Exportadores.
        /// </summary>
        public static string Btn_MyExportersGroups {
            get {
                return ResourceManager.GetString("Btn_MyExportersGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Grupos Importadores.
        /// </summary>
        public static string Btn_MyImportersGroups {
            get {
                return ResourceManager.GetString("Btn_MyImportersGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Grupos Productos.
        /// </summary>
        public static string Btn_MyProductsGroups {
            get {
                return ResourceManager.GetString("Btn_MyProductsGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Plantillas.
        /// </summary>
        public static string Btn_MyTemplates {
            get {
                return ResourceManager.GetString("Btn_MyTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre personalizado.
        /// </summary>
        public static string CustomizedName_Text {
            get {
                return ResourceManager.GetString("CustomizedName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizar Mis Plantillas Excel.
        /// </summary>
        public static string CustomizeMyExcelTemplates_Text {
            get {
                return ResourceManager.GetString("CustomizeMyExcelTemplates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizar Mis Plantillas.
        /// </summary>
        public static string CustomizeMyTemplates_Text {
            get {
                return ResourceManager.GetString("CustomizeMyTemplates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por Defecto.
        /// </summary>
        public static string Default_Text {
            get {
                return ResourceManager.GetString("Default_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Delete_Text {
            get {
                return ResourceManager.GetString("Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Favorito.
        /// </summary>
        public static string DeleteFavorite_Text {
            get {
                return ResourceManager.GetString("DeleteFavorite_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Favoritos.
        /// </summary>
        public static string DeleteFavorites_Text {
            get {
                return ResourceManager.GetString("DeleteFavorites_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Grupos seleccionados.
        /// </summary>
        public static string DeleteSelectedGroups_Text {
            get {
                return ResourceManager.GetString("DeleteSelectedGroups_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Plantilla.
        /// </summary>
        public static string DeleteTemplate_Text {
            get {
                return ResourceManager.GetString("DeleteTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En esta sección Ud. podrá editar, eliminar o cambiar de nombre a sus Favoritos o formar Grupos, juntando a varios de ellos (productos o compañias) según su criterio..
        /// </summary>
        public static string DescriptionFavorites_Text {
            get {
                return ResourceManager.GetString("DescriptionFavorites_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde esta sección Ud. podrá editar o eliminar sus Grupos de productos o compañias..
        /// </summary>
        public static string DescriptionGroups_Text {
            get {
                return ResourceManager.GetString("DescriptionGroups_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo.
        /// </summary>
        public static string Group_Text {
            get {
                return ResourceManager.GetString("Group_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Grupo.
        /// </summary>
        public static string ModifyGroup_Text {
            get {
                return ResourceManager.GetString("ModifyGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudieron eliminar todos los favoritos seleccionados. &lt;br&gt;Un grupo debe tener al menos un favorito. &lt;br&gt;Le segurimos eliminar el Grupo completo.
        /// </summary>
        public static string Msg_CouldNotDeleteAllSelectedFavorites {
            get {
                return ResourceManager.GetString("Msg_CouldNotDeleteAllSelectedFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador de Mis Favoritos y Mis Grupos.
        /// </summary>
        public static string MyFavoritesAndGroupsConfiguration_Text {
            get {
                return ResourceManager.GetString("MyFavoritesAndGroupsConfiguration_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador de Mis Favoritos .
        /// </summary>
        public static string MyFavoritesConfiguration_Text {
            get {
                return ResourceManager.GetString("MyFavoritesConfiguration_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Grupos.
        /// </summary>
        public static string MyGroups_Text {
            get {
                return ResourceManager.GetString("MyGroups_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador de Mis Grupos.
        /// </summary>
        public static string MyGroupsConfiguration_Text {
            get {
                return ResourceManager.GetString("MyGroupsConfiguration_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Plantilla.
        /// </summary>
        public static string NewTemplate_Text {
            get {
                return ResourceManager.GetString("NewTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grabar.
        /// </summary>
        public static string Save_Text {
            get {
                return ResourceManager.GetString("Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grabar Plantilla.
        /// </summary>
        public static string SaveTemplate_Text {
            get {
                return ResourceManager.GetString("SaveTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string Select_Text {
            get {
                return ResourceManager.GetString("Select_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor seleccione al menos un favorito.
        /// </summary>
        public static string SelectAtLeastOneFavorite_Text {
            get {
                return ResourceManager.GetString("SelectAtLeastOneFavorite_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor seleccione al menos un favorito a eliminar.
        /// </summary>
        public static string SelectAtLeastOneFavoriteToDelete_Text {
            get {
                return ResourceManager.GetString("SelectAtLeastOneFavoriteToDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor seleccione al menos un grupo a eliminar.
        /// </summary>
        public static string SelectAtLeastOneGroupToDelete_Text {
            get {
                return ResourceManager.GetString("SelectAtLeastOneGroupToDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizar Mis Alertas.
        /// </summary>
        public static string SettingUpMyAlerts_Text {
            get {
                return ResourceManager.GetString("SettingUpMyAlerts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizar Mis Favoritos.
        /// </summary>
        public static string SettingUpMyFavorites_Text {
            get {
                return ResourceManager.GetString("SettingUpMyFavorites_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizar Mis Grupos.
        /// </summary>
        public static string SettingUpMyGroups_Text {
            get {
                return ResourceManager.GetString("SettingUpMyGroups_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar Favoritos.
        /// </summary>
        public static string ShowFavorites_Text {
            get {
                return ResourceManager.GetString("ShowFavorites_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUC.
        /// </summary>
        public static string TaxID_Text {
            get {
                return ResourceManager.GetString("TaxID_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plantilla.
        /// </summary>
        public static string Template_Text {
            get {
                return ResourceManager.GetString("Template_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string Update_Text {
            get {
                return ResourceManager.GetString("Update_Text", resourceCulture);
            }
        }
    }
}
