//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Veritrade2017.VeritradeAdmin {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SeguridadSoap", Namespace="http://tempuri.org/")]
    public partial class Seguridad : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExisteCodUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExisteEmail1OperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Valida2OperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidaIPPaisOperationCompleted;
        
        private System.Threading.SendOrPostCallback GrabaHistorialOperationCompleted;
        
        private System.Threading.SendOrPostCallback GrabaHistorial2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GrabaHistorial3OperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidaSeguridadOperationCompleted;
        
        private System.Threading.SendOrPostCallback GrabaLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscaUbicacionIPOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscaUbicacionIP2OperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback Save3OperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtieneVariablesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Seguridad() {
            this.Url = global::Veritrade2017.Properties.Settings.Default.Veritrade2017_VeritradeAdmin_Seguridad;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExisteCodUsuarioCompletedEventHandler ExisteCodUsuarioCompleted;
        
        /// <remarks/>
        public event ExisteEmail1CompletedEventHandler ExisteEmail1Completed;
        
        /// <remarks/>
        public event ValidaCompletedEventHandler ValidaCompleted;
        
        /// <remarks/>
        public event Valida2CompletedEventHandler Valida2Completed;
        
        /// <remarks/>
        public event ValidaIPPaisCompletedEventHandler ValidaIPPaisCompleted;
        
        /// <remarks/>
        public event GrabaHistorialCompletedEventHandler GrabaHistorialCompleted;
        
        /// <remarks/>
        public event GrabaHistorial2CompletedEventHandler GrabaHistorial2Completed;
        
        /// <remarks/>
        public event GrabaHistorial3CompletedEventHandler GrabaHistorial3Completed;
        
        /// <remarks/>
        public event ValidaSeguridadCompletedEventHandler ValidaSeguridadCompleted;
        
        /// <remarks/>
        public event GrabaLogCompletedEventHandler GrabaLogCompleted;
        
        /// <remarks/>
        public event BuscaUbicacionIPCompletedEventHandler BuscaUbicacionIPCompleted;
        
        /// <remarks/>
        public event BuscaUbicacionIP2CompletedEventHandler BuscaUbicacionIP2Completed;
        
        /// <remarks/>
        public event SaveCompletedEventHandler SaveCompleted;
        
        /// <remarks/>
        public event Save3CompletedEventHandler Save3Completed;
        
        /// <remarks/>
        public event ObtieneVariablesCompletedEventHandler ObtieneVariablesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExisteCodUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ExisteCodUsuario(string CodUsuario) {
            object[] results = this.Invoke("ExisteCodUsuario", new object[] {
                        CodUsuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ExisteCodUsuarioAsync(string CodUsuario) {
            this.ExisteCodUsuarioAsync(CodUsuario, null);
        }
        
        /// <remarks/>
        public void ExisteCodUsuarioAsync(string CodUsuario, object userState) {
            if ((this.ExisteCodUsuarioOperationCompleted == null)) {
                this.ExisteCodUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExisteCodUsuarioOperationCompleted);
            }
            this.InvokeAsync("ExisteCodUsuario", new object[] {
                        CodUsuario}, this.ExisteCodUsuarioOperationCompleted, userState);
        }
        
        private void OnExisteCodUsuarioOperationCompleted(object arg) {
            if ((this.ExisteCodUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExisteCodUsuarioCompleted(this, new ExisteCodUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExisteEmail1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ExisteEmail1(string Email1) {
            object[] results = this.Invoke("ExisteEmail1", new object[] {
                        Email1});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ExisteEmail1Async(string Email1) {
            this.ExisteEmail1Async(Email1, null);
        }
        
        /// <remarks/>
        public void ExisteEmail1Async(string Email1, object userState) {
            if ((this.ExisteEmail1OperationCompleted == null)) {
                this.ExisteEmail1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnExisteEmail1OperationCompleted);
            }
            this.InvokeAsync("ExisteEmail1", new object[] {
                        Email1}, this.ExisteEmail1OperationCompleted, userState);
        }
        
        private void OnExisteEmail1OperationCompleted(object arg) {
            if ((this.ExisteEmail1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExisteEmail1Completed(this, new ExisteEmail1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Valida", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Valida(string CodUsuario, string Password, string IdAplicacion, ref string IdUsuario, ref string CodSeguridad, ref int CantUsuariosUnicos) {
            object[] results = this.Invoke("Valida", new object[] {
                        CodUsuario,
                        Password,
                        IdAplicacion,
                        IdUsuario,
                        CodSeguridad,
                        CantUsuariosUnicos});
            IdUsuario = ((string)(results[1]));
            CodSeguridad = ((string)(results[2]));
            CantUsuariosUnicos = ((int)(results[3]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidaAsync(string CodUsuario, string Password, string IdAplicacion, string IdUsuario, string CodSeguridad, int CantUsuariosUnicos) {
            this.ValidaAsync(CodUsuario, Password, IdAplicacion, IdUsuario, CodSeguridad, CantUsuariosUnicos, null);
        }
        
        /// <remarks/>
        public void ValidaAsync(string CodUsuario, string Password, string IdAplicacion, string IdUsuario, string CodSeguridad, int CantUsuariosUnicos, object userState) {
            if ((this.ValidaOperationCompleted == null)) {
                this.ValidaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidaOperationCompleted);
            }
            this.InvokeAsync("Valida", new object[] {
                        CodUsuario,
                        Password,
                        IdAplicacion,
                        IdUsuario,
                        CodSeguridad,
                        CantUsuariosUnicos}, this.ValidaOperationCompleted, userState);
        }
        
        private void OnValidaOperationCompleted(object arg) {
            if ((this.ValidaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidaCompleted(this, new ValidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Valida2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Valida2(string CodUsuario, string Password, ref string IdUsuario, ref string IdAplicacion, ref string CodSeguridad, ref int CantUsuariosUnicos) {
            object[] results = this.Invoke("Valida2", new object[] {
                        CodUsuario,
                        Password,
                        IdUsuario,
                        IdAplicacion,
                        CodSeguridad,
                        CantUsuariosUnicos});
            IdUsuario = ((string)(results[1]));
            IdAplicacion = ((string)(results[2]));
            CodSeguridad = ((string)(results[3]));
            CantUsuariosUnicos = ((int)(results[4]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Valida2Async(string CodUsuario, string Password, string IdUsuario, string IdAplicacion, string CodSeguridad, int CantUsuariosUnicos) {
            this.Valida2Async(CodUsuario, Password, IdUsuario, IdAplicacion, CodSeguridad, CantUsuariosUnicos, null);
        }
        
        /// <remarks/>
        public void Valida2Async(string CodUsuario, string Password, string IdUsuario, string IdAplicacion, string CodSeguridad, int CantUsuariosUnicos, object userState) {
            if ((this.Valida2OperationCompleted == null)) {
                this.Valida2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnValida2OperationCompleted);
            }
            this.InvokeAsync("Valida2", new object[] {
                        CodUsuario,
                        Password,
                        IdUsuario,
                        IdAplicacion,
                        CodSeguridad,
                        CantUsuariosUnicos}, this.Valida2OperationCompleted, userState);
        }
        
        private void OnValida2OperationCompleted(object arg) {
            if ((this.Valida2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Valida2Completed(this, new Valida2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidaIPPais", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidaIPPais(string IdUsuario, string DireccionIP) {
            object[] results = this.Invoke("ValidaIPPais", new object[] {
                        IdUsuario,
                        DireccionIP});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidaIPPaisAsync(string IdUsuario, string DireccionIP) {
            this.ValidaIPPaisAsync(IdUsuario, DireccionIP, null);
        }
        
        /// <remarks/>
        public void ValidaIPPaisAsync(string IdUsuario, string DireccionIP, object userState) {
            if ((this.ValidaIPPaisOperationCompleted == null)) {
                this.ValidaIPPaisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidaIPPaisOperationCompleted);
            }
            this.InvokeAsync("ValidaIPPais", new object[] {
                        IdUsuario,
                        DireccionIP}, this.ValidaIPPaisOperationCompleted, userState);
        }
        
        private void OnValidaIPPaisOperationCompleted(object arg) {
            if ((this.ValidaIPPaisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidaIPPaisCompleted(this, new ValidaIPPaisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GrabaHistorial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GrabaHistorial(string IdUsuario, string DireccionIP, string Navegador, string CodEstado) {
            this.Invoke("GrabaHistorial", new object[] {
                        IdUsuario,
                        DireccionIP,
                        Navegador,
                        CodEstado});
        }
        
        /// <remarks/>
        public void GrabaHistorialAsync(string IdUsuario, string DireccionIP, string Navegador, string CodEstado) {
            this.GrabaHistorialAsync(IdUsuario, DireccionIP, Navegador, CodEstado, null);
        }
        
        /// <remarks/>
        public void GrabaHistorialAsync(string IdUsuario, string DireccionIP, string Navegador, string CodEstado, object userState) {
            if ((this.GrabaHistorialOperationCompleted == null)) {
                this.GrabaHistorialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGrabaHistorialOperationCompleted);
            }
            this.InvokeAsync("GrabaHistorial", new object[] {
                        IdUsuario,
                        DireccionIP,
                        Navegador,
                        CodEstado}, this.GrabaHistorialOperationCompleted, userState);
        }
        
        private void OnGrabaHistorialOperationCompleted(object arg) {
            if ((this.GrabaHistorialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GrabaHistorialCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GrabaHistorial2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GrabaHistorial2(string IdUsuario, string DireccionIP, string Navegador, string ProcessorID, string MACAddress, string ComputerName, string UserName, string CodEstado) {
            this.Invoke("GrabaHistorial2", new object[] {
                        IdUsuario,
                        DireccionIP,
                        Navegador,
                        ProcessorID,
                        MACAddress,
                        ComputerName,
                        UserName,
                        CodEstado});
        }
        
        /// <remarks/>
        public void GrabaHistorial2Async(string IdUsuario, string DireccionIP, string Navegador, string ProcessorID, string MACAddress, string ComputerName, string UserName, string CodEstado) {
            this.GrabaHistorial2Async(IdUsuario, DireccionIP, Navegador, ProcessorID, MACAddress, ComputerName, UserName, CodEstado, null);
        }
        
        /// <remarks/>
        public void GrabaHistorial2Async(string IdUsuario, string DireccionIP, string Navegador, string ProcessorID, string MACAddress, string ComputerName, string UserName, string CodEstado, object userState) {
            if ((this.GrabaHistorial2OperationCompleted == null)) {
                this.GrabaHistorial2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGrabaHistorial2OperationCompleted);
            }
            this.InvokeAsync("GrabaHistorial2", new object[] {
                        IdUsuario,
                        DireccionIP,
                        Navegador,
                        ProcessorID,
                        MACAddress,
                        ComputerName,
                        UserName,
                        CodEstado}, this.GrabaHistorial2OperationCompleted, userState);
        }
        
        private void OnGrabaHistorial2OperationCompleted(object arg) {
            if ((this.GrabaHistorial2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GrabaHistorial2Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GrabaHistorial3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GrabaHistorial3(string IdUsuario, string DireccionIP, string Navegador, string ProcessorID, string MACAddress, string ComputerName, string UserName, string VersionLogin, string CodEstado) {
            this.Invoke("GrabaHistorial3", new object[] {
                        IdUsuario,
                        DireccionIP,
                        Navegador,
                        ProcessorID,
                        MACAddress,
                        ComputerName,
                        UserName,
                        VersionLogin,
                        CodEstado});
        }
        
        /// <remarks/>
        public void GrabaHistorial3Async(string IdUsuario, string DireccionIP, string Navegador, string ProcessorID, string MACAddress, string ComputerName, string UserName, string VersionLogin, string CodEstado) {
            this.GrabaHistorial3Async(IdUsuario, DireccionIP, Navegador, ProcessorID, MACAddress, ComputerName, UserName, VersionLogin, CodEstado, null);
        }
        
        /// <remarks/>
        public void GrabaHistorial3Async(string IdUsuario, string DireccionIP, string Navegador, string ProcessorID, string MACAddress, string ComputerName, string UserName, string VersionLogin, string CodEstado, object userState) {
            if ((this.GrabaHistorial3OperationCompleted == null)) {
                this.GrabaHistorial3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGrabaHistorial3OperationCompleted);
            }
            this.InvokeAsync("GrabaHistorial3", new object[] {
                        IdUsuario,
                        DireccionIP,
                        Navegador,
                        ProcessorID,
                        MACAddress,
                        ComputerName,
                        UserName,
                        VersionLogin,
                        CodEstado}, this.GrabaHistorial3OperationCompleted, userState);
        }
        
        private void OnGrabaHistorial3OperationCompleted(object arg) {
            if ((this.GrabaHistorial3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GrabaHistorial3Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidaSeguridad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidaSeguridad(string IdUsuario, int CantUsuariosUnicos, string ProcessorID, string MACAddress, string ComputerName, string UserName, string VersionLogin) {
            object[] results = this.Invoke("ValidaSeguridad", new object[] {
                        IdUsuario,
                        CantUsuariosUnicos,
                        ProcessorID,
                        MACAddress,
                        ComputerName,
                        UserName,
                        VersionLogin});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidaSeguridadAsync(string IdUsuario, int CantUsuariosUnicos, string ProcessorID, string MACAddress, string ComputerName, string UserName, string VersionLogin) {
            this.ValidaSeguridadAsync(IdUsuario, CantUsuariosUnicos, ProcessorID, MACAddress, ComputerName, UserName, VersionLogin, null);
        }
        
        /// <remarks/>
        public void ValidaSeguridadAsync(string IdUsuario, int CantUsuariosUnicos, string ProcessorID, string MACAddress, string ComputerName, string UserName, string VersionLogin, object userState) {
            if ((this.ValidaSeguridadOperationCompleted == null)) {
                this.ValidaSeguridadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidaSeguridadOperationCompleted);
            }
            this.InvokeAsync("ValidaSeguridad", new object[] {
                        IdUsuario,
                        CantUsuariosUnicos,
                        ProcessorID,
                        MACAddress,
                        ComputerName,
                        UserName,
                        VersionLogin}, this.ValidaSeguridadOperationCompleted, userState);
        }
        
        private void OnValidaSeguridadOperationCompleted(object arg) {
            if ((this.ValidaSeguridadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidaSeguridadCompleted(this, new ValidaSeguridadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GrabaLog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GrabaLog(int IdUsuario, string Logs) {
            this.Invoke("GrabaLog", new object[] {
                        IdUsuario,
                        Logs});
        }
        
        /// <remarks/>
        public void GrabaLogAsync(int IdUsuario, string Logs) {
            this.GrabaLogAsync(IdUsuario, Logs, null);
        }
        
        /// <remarks/>
        public void GrabaLogAsync(int IdUsuario, string Logs, object userState) {
            if ((this.GrabaLogOperationCompleted == null)) {
                this.GrabaLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGrabaLogOperationCompleted);
            }
            this.InvokeAsync("GrabaLog", new object[] {
                        IdUsuario,
                        Logs}, this.GrabaLogOperationCompleted, userState);
        }
        
        private void OnGrabaLogOperationCompleted(object arg) {
            if ((this.GrabaLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GrabaLogCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscaUbicacionIP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BuscaUbicacionIP(string DireccionIP) {
            object[] results = this.Invoke("BuscaUbicacionIP", new object[] {
                        DireccionIP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BuscaUbicacionIPAsync(string DireccionIP) {
            this.BuscaUbicacionIPAsync(DireccionIP, null);
        }
        
        /// <remarks/>
        public void BuscaUbicacionIPAsync(string DireccionIP, object userState) {
            if ((this.BuscaUbicacionIPOperationCompleted == null)) {
                this.BuscaUbicacionIPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscaUbicacionIPOperationCompleted);
            }
            this.InvokeAsync("BuscaUbicacionIP", new object[] {
                        DireccionIP}, this.BuscaUbicacionIPOperationCompleted, userState);
        }
        
        private void OnBuscaUbicacionIPOperationCompleted(object arg) {
            if ((this.BuscaUbicacionIPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscaUbicacionIPCompleted(this, new BuscaUbicacionIPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscaUbicacionIP2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BuscaUbicacionIP2(string DireccionIP, ref string CodPais) {
            try
            {
				object[] results = this.Invoke("BuscaUbicacionIP2", new object[] {
						DireccionIP,
						CodPais});
				CodPais = ((string)(results[1]));
				return ((string)(results[0]));

			}
            catch (Exception ex)
            {

                return "";
            }
        
        }
        
        /// <remarks/>
        public void BuscaUbicacionIP2Async(string DireccionIP, string CodPais) {
            this.BuscaUbicacionIP2Async(DireccionIP, CodPais, null);
        }
        
        /// <remarks/>
        public void BuscaUbicacionIP2Async(string DireccionIP, string CodPais, object userState) {
            if ((this.BuscaUbicacionIP2OperationCompleted == null)) {
                this.BuscaUbicacionIP2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscaUbicacionIP2OperationCompleted);
            }
            this.InvokeAsync("BuscaUbicacionIP2", new object[] {
                        DireccionIP,
                        CodPais}, this.BuscaUbicacionIP2OperationCompleted, userState);
        }
        
        private void OnBuscaUbicacionIP2OperationCompleted(object arg) {
            if ((this.BuscaUbicacionIP2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscaUbicacionIP2Completed(this, new BuscaUbicacionIP2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Save", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Save(string A, string B, string C, string D, string E, string F) {
            object[] results = this.Invoke("Save", new object[] {
                        A,
                        B,
                        C,
                        D,
                        E,
                        F});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SaveAsync(string A, string B, string C, string D, string E, string F) {
            this.SaveAsync(A, B, C, D, E, F, null);
        }
        
        /// <remarks/>
        public void SaveAsync(string A, string B, string C, string D, string E, string F, object userState) {
            if ((this.SaveOperationCompleted == null)) {
                this.SaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveOperationCompleted);
            }
            this.InvokeAsync("Save", new object[] {
                        A,
                        B,
                        C,
                        D,
                        E,
                        F}, this.SaveOperationCompleted, userState);
        }
        
        private void OnSaveOperationCompleted(object arg) {
            if ((this.SaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCompleted(this, new SaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Save3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Save3(string CodUsuario, string Password, string ProcessorID, string MACAddress, string ComputerName, string UserName, string Validador, ref string IdUsuario) {
            object[] results = this.Invoke("Save3", new object[] {
                        CodUsuario,
                        Password,
                        ProcessorID,
                        MACAddress,
                        ComputerName,
                        UserName,
                        Validador,
                        IdUsuario});
            IdUsuario = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Save3Async(string CodUsuario, string Password, string ProcessorID, string MACAddress, string ComputerName, string UserName, string Validador, string IdUsuario) {
            this.Save3Async(CodUsuario, Password, ProcessorID, MACAddress, ComputerName, UserName, Validador, IdUsuario, null);
        }
        
        /// <remarks/>
        public void Save3Async(string CodUsuario, string Password, string ProcessorID, string MACAddress, string ComputerName, string UserName, string Validador, string IdUsuario, object userState) {
            if ((this.Save3OperationCompleted == null)) {
                this.Save3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSave3OperationCompleted);
            }
            this.InvokeAsync("Save3", new object[] {
                        CodUsuario,
                        Password,
                        ProcessorID,
                        MACAddress,
                        ComputerName,
                        UserName,
                        Validador,
                        IdUsuario}, this.Save3OperationCompleted, userState);
        }
        
        private void OnSave3OperationCompleted(object arg) {
            if ((this.Save3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Save3Completed(this, new Save3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtieneVariables", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ObtieneVariables(string IdHistorial, ref string CodUsuario, ref string Password, ref string ProcessorID, ref string MACAddress, ref string ComputerName, ref string UserName) {
            object[] results = this.Invoke("ObtieneVariables", new object[] {
                        IdHistorial,
                        CodUsuario,
                        Password,
                        ProcessorID,
                        MACAddress,
                        ComputerName,
                        UserName});
            CodUsuario = ((string)(results[1]));
            Password = ((string)(results[2]));
            ProcessorID = ((string)(results[3]));
            MACAddress = ((string)(results[4]));
            ComputerName = ((string)(results[5]));
            UserName = ((string)(results[6]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ObtieneVariablesAsync(string IdHistorial, string CodUsuario, string Password, string ProcessorID, string MACAddress, string ComputerName, string UserName) {
            this.ObtieneVariablesAsync(IdHistorial, CodUsuario, Password, ProcessorID, MACAddress, ComputerName, UserName, null);
        }
        
        /// <remarks/>
        public void ObtieneVariablesAsync(string IdHistorial, string CodUsuario, string Password, string ProcessorID, string MACAddress, string ComputerName, string UserName, object userState) {
            if ((this.ObtieneVariablesOperationCompleted == null)) {
                this.ObtieneVariablesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtieneVariablesOperationCompleted);
            }
            this.InvokeAsync("ObtieneVariables", new object[] {
                        IdHistorial,
                        CodUsuario,
                        Password,
                        ProcessorID,
                        MACAddress,
                        ComputerName,
                        UserName}, this.ObtieneVariablesOperationCompleted, userState);
        }
        
        private void OnObtieneVariablesOperationCompleted(object arg) {
            if ((this.ObtieneVariablesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtieneVariablesCompleted(this, new ObtieneVariablesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ExisteCodUsuarioCompletedEventHandler(object sender, ExisteCodUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExisteCodUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExisteCodUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ExisteEmail1CompletedEventHandler(object sender, ExisteEmail1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExisteEmail1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExisteEmail1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ValidaCompletedEventHandler(object sender, ValidaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string IdUsuario {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string CodSeguridad {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public int CantUsuariosUnicos {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Valida2CompletedEventHandler(object sender, Valida2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Valida2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Valida2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string IdUsuario {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string IdAplicacion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string CodSeguridad {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public int CantUsuariosUnicos {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[4]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ValidaIPPaisCompletedEventHandler(object sender, ValidaIPPaisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidaIPPaisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidaIPPaisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GrabaHistorialCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GrabaHistorial2CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GrabaHistorial3CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ValidaSeguridadCompletedEventHandler(object sender, ValidaSeguridadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidaSeguridadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidaSeguridadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GrabaLogCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscaUbicacionIPCompletedEventHandler(object sender, BuscaUbicacionIPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscaUbicacionIPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscaUbicacionIPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscaUbicacionIP2CompletedEventHandler(object sender, BuscaUbicacionIP2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscaUbicacionIP2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscaUbicacionIP2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string CodPais {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SaveCompletedEventHandler(object sender, SaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Save3CompletedEventHandler(object sender, Save3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Save3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Save3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string IdUsuario {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ObtieneVariablesCompletedEventHandler(object sender, ObtieneVariablesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtieneVariablesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtieneVariablesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string CodUsuario {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string ProcessorID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string MACAddress {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string ComputerName {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
    }
}

#pragma warning restore 1591