//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductProfileResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductProfileResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ProductProfileResources", typeof(ProductProfileResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio Promedio US$ / KILOGRAMOS.
        /// </summary>
        public static string Average_Price {
            get {
                return ResourceManager.GetString("Average_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importadores.
        /// </summary>
        public static string Block02_Subtitle01 {
            get {
                return ResourceManager.GetString("Block02_Subtitle01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportadores.
        /// </summary>
        public static string Block02_Subtitle02 {
            get {
                return ResourceManager.GetString("Block02_Subtitle02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para mayor informacion solicite una.
        /// </summary>
        public static string Box_Trial_01 {
            get {
                return ResourceManager.GetString("Box_Trial_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba gratis.
        /// </summary>
        public static string Box_Trial_02 {
            get {
                return ResourceManager.GetString("Box_Trial_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No registra información.
        /// </summary>
        public static string Chart_Empty {
            get {
                return ResourceManager.GetString("Chart_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comparativo FOB US$.
        /// </summary>
        public static string CIF_FOB_Comparative {
            get {
                return ResourceManager.GetString("CIF_FOB_Comparative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor CIF Importado US$.
        /// </summary>
        public static string CIF_Imported {
            get {
                return ResourceManager.GetString("CIF_Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Países.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportado.
        /// </summary>
        public static string Exported {
            get {
                return ResourceManager.GetString("Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string Exported_Quantity_01 {
            get {
                return ResourceManager.GetString("Exported_Quantity_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportada.
        /// </summary>
        public static string Exported_Quantity_02 {
            get {
                return ResourceManager.GetString("Exported_Quantity_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportador.
        /// </summary>
        public static string Exporter {
            get {
                return ResourceManager.GetString("Exporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportaciones.
        /// </summary>
        public static string Exports {
            get {
                return ResourceManager.GetString("Exports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor FOB Exportado US$.
        /// </summary>
        public static string FOB_Exported {
            get {
                return ResourceManager.GetString("FOB_Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRUEBA GRATUITA AQUÍ.
        /// </summary>
        public static string Free_trial {
            get {
                return ResourceManager.GetString("Free_trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importado.
        /// </summary>
        public static string Imported {
            get {
                return ResourceManager.GetString("Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string Imported_Quantity_01 {
            get {
                return ResourceManager.GetString("Imported_Quantity_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importada.
        /// </summary>
        public static string Imported_Quantity_02 {
            get {
                return ResourceManager.GetString("Imported_Quantity_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importador.
        /// </summary>
        public static string Importer {
            get {
                return ResourceManager.GetString("Importer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importaciones.
        /// </summary>
        public static string Imports {
            get {
                return ResourceManager.GetString("Imports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importaciones y Exportaciones.
        /// </summary>
        public static string Imports_Exports {
            get {
                return ResourceManager.GetString("Imports_Exports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kilogramos.
        /// </summary>
        public static string Kg {
            get {
                return ResourceManager.GetString("Kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No especificado.
        /// </summary>
        public static string Not_Specified {
            get {
                return ResourceManager.GetString("Not_Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Digite el nombre de un producto o la partida arancelaria a 6 dígitos.
        /// </summary>
        public static string Productos_Buscar_Content_SubTitle {
            get {
                return ResourceManager.GetString("Productos_Buscar_Content_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principales Países de Destino.
        /// </summary>
        public static string Ranking_Country_Exp {
            get {
                return ResourceManager.GetString("Ranking_Country_Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principales Países de Origen.
        /// </summary>
        public static string Ranking_Country_Imp {
            get {
                return ResourceManager.GetString("Ranking_Country_Imp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principales Exportadores.
        /// </summary>
        public static string Ranking_Exporters {
            get {
                return ResourceManager.GetString("Ranking_Exporters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principales Importadores.
        /// </summary>
        public static string Ranking_Importers {
            get {
                return ResourceManager.GetString("Ranking_Importers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registros.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar tu producto o partida.
        /// </summary>
        public static string Search_Product {
            get {
                return ResourceManager.GetString("Search_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen Período.
        /// </summary>
        public static string Summary_Period {
            get {
                return ResourceManager.GetString("Summary_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio Promedio.
        /// </summary>
        public static string Table_Average_Price {
            get {
                return ResourceManager.GetString("Table_Average_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OTRAS PARTIDAS RELACIONADAS.
        /// </summary>
        public static string Table01_Title {
            get {
                return ResourceManager.GetString("Table01_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esto es solo una muestra de lo que Veritrade puede ofrecer..
        /// </summary>
        public static string Table02_Description_01 {
            get {
                return ResourceManager.GetString("Table02_Description_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicita una prueba gratis y conoce más..
        /// </summary>
        public static string Table02_Description_02 {
            get {
                return ResourceManager.GetString("Table02_Description_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Te gustó lo que viste?.
        /// </summary>
        public static string Table02_Title {
            get {
                return ResourceManager.GetString("Table02_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Productos.
        /// </summary>
        public static string Title_Landing {
            get {
                return ResourceManager.GetString("Title_Landing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil Producto.
        /// </summary>
        public static string Title_Profile {
            get {
                return ResourceManager.GetString("Title_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string Unit_Price_01 {
            get {
                return ResourceManager.GetString("Unit_Price_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unitario.
        /// </summary>
        public static string Unit_Price_02 {
            get {
                return ResourceManager.GetString("Unit_Price_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
