//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar Filtros.
        /// </summary>
        public static string Add_Filter_Search_Button {
            get {
                return ResourceManager.GetString("Add_Filter_Search_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acepto los.
        /// </summary>
        public static string Agree_Text {
            get {
                return ResourceManager.GetString("Agree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noticias anteriores.
        /// </summary>
        public static string Archive_Text {
            get {
                return ResourceManager.GetString("Archive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprar.
        /// </summary>
        public static string Btn_Comprar {
            get {
                return ResourceManager.GetString("Btn_Comprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contáctanos.
        /// </summary>
        public static string Btn_Contactanos {
            get {
                return ResourceManager.GetString("Btn_Contactanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes a tu medida aquí.
        /// </summary>
        public static string Btn_Planes {
            get {
                return ResourceManager.GetString("Btn_Planes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        public static string Button_Continue {
            get {
                return ResourceManager.GetString("Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar muestra.
        /// </summary>
        public static string Button_Download {
            get {
                return ResourceManager.GetString("Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa a tu cuenta en Veritrade.
        /// </summary>
        public static string Button_GoHome {
            get {
                return ResourceManager.GetString("Button_GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagar.
        /// </summary>
        public static string Button_Pay {
            get {
                return ResourceManager.GetString("Button_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Close_Text {
            get {
                return ResourceManager.GetString("Close_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le enviaremos un &lt;span&gt;correo electrónico&lt;/span&gt; con la confirmación y los datos de su compra.
        /// </summary>
        public static string Compra_Confirmacion_Mensaje {
            get {
                return ResourceManager.GetString("Compra_Confirmacion_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Gracias por tu &lt;span&gt;Compra!&lt;/span&gt;.
        /// </summary>
        public static string Compra_Confirmacion_Titulo {
            get {
                return ResourceManager.GetString("Compra_Confirmacion_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string Compra_Pedido_Direccion {
            get {
                return ResourceManager.GetString("Compra_Pedido_Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Más IGV.
        /// </summary>
        public static string Compra_Pedido_Igv {
            get {
                return ResourceManager.GetString("Compra_Pedido_Igv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Más IVA.
        /// </summary>
        public static string Compra_Pedido_Iva {
            get {
                return ResourceManager.GetString("Compra_Pedido_Iva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón Social.
        /// </summary>
        public static string Compra_Pedido_RazonSocial {
            get {
                return ResourceManager.GetString("Compra_Pedido_RazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruc.
        /// </summary>
        public static string Compra_Pedido_Ruc {
            get {
                return ResourceManager.GetString("Compra_Pedido_Ruc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto a las ventas (sólo en NY).
        /// </summary>
        public static string Compra_Pedido_Tax {
            get {
                return ResourceManager.GetString("Compra_Pedido_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículo.
        /// </summary>
        public static string Compra_Pedido_Titulo01 {
            get {
                return ResourceManager.GetString("Compra_Pedido_Titulo01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen.
        /// </summary>
        public static string Compra_Pedido_Titulo02 {
            get {
                return ResourceManager.GetString("Compra_Pedido_Titulo02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string Compra_Pedido_Titulo03 {
            get {
                return ResourceManager.GetString("Compra_Pedido_Titulo03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Compra_Pedido_Total {
            get {
                return ResourceManager.GetString("Compra_Pedido_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra.
        /// </summary>
        public static string Compra_Text {
            get {
                return ResourceManager.GetString("Compra_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su Pedido.
        /// </summary>
        public static string Compra_Titulo01 {
            get {
                return ResourceManager.GetString("Compra_Titulo01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registre su Usuario en Veritrade.
        /// </summary>
        public static string Compra_Titulo02 {
            get {
                return ResourceManager.GetString("Compra_Titulo02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de su pago.
        /// </summary>
        public static string Compra_Titulo03 {
            get {
                return ResourceManager.GetString("Compra_Titulo03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted ya cuenta con un plan vigente, cualquier duda sobre nuestros planes &lt;a class=&quot;contactenos&quot;&gt;contáctenos&lt;/a&gt;.
        /// </summary>
        public static string Compra_Verificacion_Mensaje {
            get {
                return ResourceManager.GetString("Compra_Verificacion_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificación de Usuario.
        /// </summary>
        public static string Compra_Verificacion_Titulo {
            get {
                return ResourceManager.GetString("Compra_Verificacion_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aduanas.
        /// </summary>
        public static string Demo_Aduanas_Tab {
            get {
                return ResourceManager.GetString("Demo_Aduanas_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcas.
        /// </summary>
        public static string Demo_Brands_Tab {
            get {
                return ResourceManager.GetString("Demo_Brands_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bultos.
        /// </summary>
        public static string Demo_Bultos {
            get {
                return ResourceManager.GetString("Demo_Bultos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aduanas - DUAs.
        /// </summary>
        public static string Demo_CustomsDuas_Tab {
            get {
                return ResourceManager.GetString("Demo_CustomsDuas_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción Adicional.
        /// </summary>
        public static string Demo_DescAdicional {
            get {
                return ResourceManager.GetString("Demo_DescAdicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Países Destino.
        /// </summary>
        public static string Demo_DestinationCountries_Tab {
            get {
                return ResourceManager.GetString("Demo_DestinationCountries_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País Destino.
        /// </summary>
        public static string Demo_DestinationCountry {
            get {
                return ResourceManager.GetString("Demo_DestinationCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle - Excel.
        /// </summary>
        public static string Demo_DetailExcel_Tab {
            get {
                return ResourceManager.GetString("Demo_DetailExcel_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distritos.
        /// </summary>
        public static string Demo_Districts_Tab {
            get {
                return ResourceManager.GetString("Demo_Districts_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si lo desea, puede descargar los resultados del tab.
        /// </summary>
        public static string Demo_ExcelDonwloadMessage_Part1 {
            get {
                return ResourceManager.GetString("Demo_ExcelDonwloadMessage_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a un archivo excel:.
        /// </summary>
        public static string Demo_ExcelDonwloadMessage_Part2 {
            get {
                return ResourceManager.GetString("Demo_ExcelDonwloadMessage_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportadores.
        /// </summary>
        public static string Demo_Exporters_Tab {
            get {
                return ResourceManager.GetString("Demo_Exporters_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportadores / Embarcadores.
        /// </summary>
        public static string Demo_Exporters_Tab_Manif {
            get {
                return ResourceManager.GetString("Demo_Exporters_Tab_Manif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importadores.
        /// </summary>
        public static string Demo_Importers_Tab {
            get {
                return ResourceManager.GetString("Demo_Importers_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importadores / Consignatarios.
        /// </summary>
        public static string Demo_Importers_Tab_Manif {
            get {
                return ResourceManager.GetString("Demo_Importers_Tab_Manif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifiesto.
        /// </summary>
        public static string Demo_Manifiesto {
            get {
                return ResourceManager.GetString("Demo_Manifiesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifiestos.
        /// </summary>
        public static string Demo_Manifiesto_Tab {
            get {
                return ResourceManager.GetString("Demo_Manifiesto_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelos.
        /// </summary>
        public static string Demo_Models_Tab {
            get {
                return ResourceManager.GetString("Demo_Models_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Tab.
        /// </summary>
        public static string Demo_New_Tab {
            get {
                return ResourceManager.GetString("Demo_New_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tramitadores / Notificados.
        /// </summary>
        public static string Demo_Notif_Tab {
            get {
                return ResourceManager.GetString("Demo_Notif_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tramitador / Notificado.
        /// </summary>
        public static string Demo_Notif_Tab_2 {
            get {
                return ResourceManager.GetString("Demo_Notif_Tab_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificado.
        /// </summary>
        public static string Demo_Notif_Tab_Fil {
            get {
                return ResourceManager.GetString("Demo_Notif_Tab_Fil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Países Origen.
        /// </summary>
        public static string Demo_OriginCountries_Tab {
            get {
                return ResourceManager.GetString("Demo_OriginCountries_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País Origen.
        /// </summary>
        public static string Demo_OriginCountry {
            get {
                return ResourceManager.GetString("Demo_OriginCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string Demo_Products_Tab {
            get {
                return ResourceManager.GetString("Demo_Products_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto Descarga.
        /// </summary>
        public static string Demo_PtoDescarga {
            get {
                return ResourceManager.GetString("Demo_PtoDescarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puertos Descarga.
        /// </summary>
        public static string Demo_PtoDescarga_Tab {
            get {
                return ResourceManager.GetString("Demo_PtoDescarga_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto Destino.
        /// </summary>
        public static string Demo_PtoDestino {
            get {
                return ResourceManager.GetString("Demo_PtoDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puertos Destino.
        /// </summary>
        public static string Demo_PtoDestino_Tab {
            get {
                return ResourceManager.GetString("Demo_PtoDestino_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto Embarque.
        /// </summary>
        public static string Demo_PtoEmbarque {
            get {
                return ResourceManager.GetString("Demo_PtoEmbarque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Últimos Puertos Embarque.
        /// </summary>
        public static string Demo_PtoEmbarque_Tab {
            get {
                return ResourceManager.GetString("Demo_PtoEmbarque_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen.
        /// </summary>
        public static string Demo_Summay_Tab {
            get {
                return ResourceManager.GetString("Demo_Summay_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vías Transporte.
        /// </summary>
        public static string Demo_Vias_Tab {
            get {
                return ResourceManager.GetString("Demo_Vias_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su Usuario y/o Contraseña no han sido ingresados correctamente..
        /// </summary>
        public static string desc_title1 {
            get {
                return ResourceManager.GetString("desc_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error al enviar el correo.
        /// </summary>
        public static string desc_title10 {
            get {
                return ResourceManager.GetString("desc_title10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor vuelva a intentarlo..
        /// </summary>
        public static string desc_title2 {
            get {
                return ResourceManager.GetString("desc_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si olvidó su Usuario y/ o Clave, por favor .
        /// </summary>
        public static string desc_title3 {
            get {
                return ResourceManager.GetString("desc_title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pude ingresar debido a que su usuario se encuentra Inactivo en Veritrade..
        /// </summary>
        public static string desc_title4 {
            get {
                return ResourceManager.GetString("desc_title4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si desea activarlo, por favor.
        /// </summary>
        public static string desc_title5 {
            get {
                return ResourceManager.GetString("desc_title5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos, este usuario no tiene acceso desde este país..
        /// </summary>
        public static string desc_title6 {
            get {
                return ResourceManager.GetString("desc_title6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si tiene una consulta, por favor .
        /// </summary>
        public static string desc_title7 {
            get {
                return ResourceManager.GetString("desc_title7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si Ud. aún no es cliente de Veritrade, inicie su: .
        /// </summary>
        public static string desc_title8 {
            get {
                return ResourceManager.GetString("desc_title8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , por favor .
        /// </summary>
        public static string desc_title9 {
            get {
                return ResourceManager.GetString("desc_title9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País Destino.
        /// </summary>
        public static string DestinationCountry_FormField_Label {
            get {
                return ResourceManager.GetString("DestinationCountry_FormField_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elgatofelix.
        /// </summary>
        public static string EmailEnvioPassword {
            get {
                return ResourceManager.GetString("EmailEnvioPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País Embarque.
        /// </summary>
        public static string EmbarqueCountry_FormField_Label {
            get {
                return ResourceManager.GetString("EmbarqueCountry_FormField_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos de importaciones y exportaciones que necesitas para hacer crecer tu negocio.
        /// </summary>
        public static string Empresas_Buscar_Content_Subtitle {
            get {
                return ResourceManager.GetString("Empresas_Buscar_Content_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encuentra la información más completa sobre comercio exterior de &lt;span&gt;latinoamerica&lt;/span&gt; y el &lt;span&gt;mundo&lt;/span&gt;  en un sólo click..
        /// </summary>
        public static string Empresas_Buscar_Content_Title {
            get {
                return ResourceManager.GetString("Empresas_Buscar_Content_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encuentre empresas por nombre o número de  identificación por cada país y accede a  información sobre comercio exterior en latinoamérica y el mundo. ¡Solicite su demo!..
        /// </summary>
        public static string Empresas_Buscar_Seo_Description {
            get {
                return ResourceManager.GetString("Empresas_Buscar_Seo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar empresas de importaciones y exportaciones por nombre.
        /// </summary>
        public static string Empresas_Buscar_Seo_Title {
            get {
                return ResourceManager.GetString("Empresas_Buscar_Seo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string Field_Company_Text {
            get {
                return ResourceManager.GetString("Field_Company_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Field_Country_Text {
            get {
                return ResourceManager.GetString("Field_Country_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string Field_Email_Text {
            get {
                return ResourceManager.GetString("Field_Email_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail (Usuario).
        /// </summary>
        public static string Field_EmailUser_Text {
            get {
                return ResourceManager.GetString("Field_EmailUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombres.
        /// </summary>
        public static string Field_FirstName_Text {
            get {
                return ResourceManager.GetString("Field_FirstName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Completo.
        /// </summary>
        public static string Field_Fullname_Text {
            get {
                return ResourceManager.GetString("Field_Fullname_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string Field_LastNames_Text {
            get {
                return ResourceManager.GetString("Field_LastNames_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string Field_Message_Text {
            get {
                return ResourceManager.GetString("Field_Message_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre y Apellidos.
        /// </summary>
        public static string Field_Names_Text {
            get {
                return ResourceManager.GetString("Field_Names_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string Field_Phone_Text {
            get {
                return ResourceManager.GetString("Field_Phone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar a Filtros.
        /// </summary>
        public static string Filters_AddButton {
            get {
                return ResourceManager.GetString("Filters_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar seleccionados.
        /// </summary>
        public static string Filters_DeleteButton {
            get {
                return ResourceManager.GetString("Filters_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor seleccione el(los) filtro(s) a eliminar.
        /// </summary>
        public static string Filters_Message_Modal {
            get {
                return ResourceManager.GetString("Filters_Message_Modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los derechos reservados.
        /// </summary>
        public static string Footer_AllRightsReserved {
            get {
                return ResourceManager.GetString("Footer_AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Footer_Email {
            get {
                return ResourceManager.GetString("Footer_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfonos.
        /// </summary>
        public static string Footer_Phone {
            get {
                return ResourceManager.GetString("Footer_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búscanos en.
        /// </summary>
        public static string Footer_Searchby {
            get {
                return ResourceManager.GetString("Footer_Searchby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa del sitio.
        /// </summary>
        public static string Footer_SiteMap {
            get {
                return ResourceManager.GetString("Footer_SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Términos y condiciones.
        /// </summary>
        public static string Footer_TermsConditions {
            get {
                return ResourceManager.GetString("Footer_TermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa.
        /// </summary>
        public static string FreeTrial_Button_Send {
            get {
                return ResourceManager.GetString("FreeTrial_Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	  
        ///		&lt;p&gt;Con &lt;strong&gt;Veritrade&lt;/strong&gt; accede a:&lt;/p&gt;
        ///                    &lt;ul class=&quot;ul-puntos-verdes&quot;&gt;
        ///                      &lt;li&gt;Información de nuevos clientes, proveedores y precios de productos.&lt;/li&gt;
        ///                      &lt;li&gt;Datos de tu competencia.&lt;/li&gt;
        ///                      &lt;li&gt;Oportunidades de negocio.&lt;/li&gt;
        ///                    &lt;/ul&gt;
        ///	 
        ///	.
        /// </summary>
        public static string FreeTrial_Content_Slide_01 {
            get {
                return ResourceManager.GetString("FreeTrial_Content_Slide_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La plataforma digital de comercio exterior para hacer crecer tu negocio..
        /// </summary>
        public static string FreeTrial_Title_Slide_01 {
            get {
                return ResourceManager.GetString("FreeTrial_Title_Slide_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de nuevos clientes, proveedores y precios de productos..
        /// </summary>
        public static string FreeTrial_Title_Slide_02 {
            get {
                return ResourceManager.GetString("FreeTrial_Title_Slide_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de la competencia..
        /// </summary>
        public static string FreeTrial_Title_Slide_03 {
            get {
                return ResourceManager.GetString("FreeTrial_Title_Slide_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oportunidades de negocio..
        /// </summary>
        public static string FreeTrial_Title_Slide_04 {
            get {
                return ResourceManager.GetString("FreeTrial_Title_Slide_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Estás a un paso de hacer crecer tu negocio!.
        /// </summary>
        public static string FreeTrial_Title01 {
            get {
                return ResourceManager.GetString("FreeTrial_Title01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicita nuestra prueba gratis.
        /// </summary>
        public static string FreeTrial_Title02 {
            get {
                return ResourceManager.GetString("FreeTrial_Title02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Registros.
        /// </summary>
        public static string Grid_Column_SeeRecords {
            get {
                return ResourceManager.GetString("Grid_Column_SeeRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros.
        /// </summary>
        public static string Grid_Column_TotalRecords {
            get {
                return ResourceManager.GetString("Grid_Column_TotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aduanas.
        /// </summary>
        public static string Grid_ColumnHeader_Customs {
            get {
                return ResourceManager.GetString("Grid_ColumnHeader_Customs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUAs.
        /// </summary>
        public static string Grid_ColumnHeader_Duas {
            get {
                return ResourceManager.GetString("Grid_ColumnHeader_Duas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOB.
        /// </summary>
        public static string Grid_ColumnHeader_ExportCIF {
            get {
                return ResourceManager.GetString("Grid_ColumnHeader_ExportCIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIF.
        /// </summary>
        public static string Grid_ColumnHeader_ImportCIF {
            get {
                return ResourceManager.GetString("Grid_ColumnHeader_ImportCIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string Home_Content_Title01 {
            get {
                return ResourceManager.GetString("Home_Content_Title01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bases de Datos actualizadas al:.
        /// </summary>
        public static string Home_Content_Title02 {
            get {
                return ResourceManager.GetString("Home_Content_Title02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver todos los Países &gt;.
        /// </summary>
        public static string Home_Countries_Button {
            get {
                return ResourceManager.GetString("Home_Countries_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros Clientes.
        /// </summary>
        public static string Home_Modal_Clientes_Title {
            get {
                return ResourceManager.GetString("Home_Modal_Clientes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizaciones de Base de Datos.
        /// </summary>
        public static string Home_Modal_Pais_Title {
            get {
                return ResourceManager.GetString("Home_Modal_Pais_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partida arancelaria.
        /// </summary>
        public static string Home_Search_Cbo_Item01 {
            get {
                return ResourceManager.GetString("Home_Search_Cbo_Item01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción comercial.
        /// </summary>
        public static string Home_Search_Cbo_Item02 {
            get {
                return ResourceManager.GetString("Home_Search_Cbo_Item02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la empresa.
        /// </summary>
        public static string Home_Search_Company {
            get {
                return ResourceManager.GetString("Home_Search_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite el nombre de la empresa.
        /// </summary>
        public static string Home_Search_Company_Placeholder {
            get {
                return ResourceManager.GetString("Home_Search_Company_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interesado en (*).
        /// </summary>
        public static string Home_Search_Item01 {
            get {
                return ResourceManager.GetString("Home_Search_Item01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Régimen (*).
        /// </summary>
        public static string Home_Search_Item02 {
            get {
                return ResourceManager.GetString("Home_Search_Item02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizar la búsqueda por.
        /// </summary>
        public static string Home_Search_Item03 {
            get {
                return ResourceManager.GetString("Home_Search_Item03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción del producto.
        /// </summary>
        public static string Home_Search_Product {
            get {
                return ResourceManager.GetString("Home_Search_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite el nombre del producto o la partida arancelaria a 6 dígitos.
        /// </summary>
        public static string Home_Search_Product_Placeholder {
            get {
                return ResourceManager.GetString("Home_Search_Product_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importaciones.
        /// </summary>
        public static string Home_Search_Radio_Item01 {
            get {
                return ResourceManager.GetString("Home_Search_Radio_Item01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportaciones.
        /// </summary>
        public static string Home_Search_Radio_Item02 {
            get {
                return ResourceManager.GetString("Home_Search_Radio_Item02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por Empresa.
        /// </summary>
        public static string Home_Search_Tab01 {
            get {
                return ResourceManager.GetString("Home_Search_Tab01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda Avanzada.
        /// </summary>
        public static string Home_Search_Tab02 {
            get {
                return ResourceManager.GetString("Home_Search_Tab02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por Producto.
        /// </summary>
        public static string Home_Search_Tab03 {
            get {
                return ResourceManager.GetString("Home_Search_Tab03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver más &gt;.
        /// </summary>
        public static string Home_Service_Button {
            get {
                return ResourceManager.GetString("Home_Service_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseo factura.
        /// </summary>
        public static string Invoice_Text {
            get {
                return ResourceManager.GetString("Invoice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Últimas búsquedas de importaciones y exportaciones por empresa.
        /// </summary>
        public static string LastestSearch {
            get {
                return ResourceManager.GetString("LastestSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Últimas noticias.
        /// </summary>
        public static string LatestNews {
            get {
                return ResourceManager.GetString("LatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarrollado para.
        /// </summary>
        public static string LoginDevelopedLabel {
            get {
                return ResourceManager.GetString("LoginDevelopedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string LoginForgotLabel {
            get {
                return ResourceManager.GetString("LoginForgotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome, IE9, Edge y Firefox.
        /// </summary>
        public static string LoginNavegadoresLabel {
            get {
                return ResourceManager.GetString("LoginNavegadoresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string LoginPasswordLabel {
            get {
                return ResourceManager.GetString("LoginPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He leído y estoy de acuerdo con los.
        /// </summary>
        public static string LoginTerminosLabel {
            get {
                return ResourceManager.GetString("LoginTerminosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a Veritrade.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string LoginUserLabel {
            get {
                return ResourceManager.GetString("LoginUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario y password no pueden contener los siguientes caracteres.
        /// </summary>
        public static string LoginValidated_Characters {
            get {
                return ResourceManager.GetString("LoginValidated_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su contraseña.
        /// </summary>
        public static string LoginValidated_Pwd {
            get {
                return ResourceManager.GetString("LoginValidated_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe aceptar los t\u00E9rminos y condiciones.
        /// </summary>
        public static string LoginValidated_Terms {
            get {
                return ResourceManager.GetString("LoginValidated_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su usuario.
        /// </summary>
        public static string LoginValidated_User {
            get {
                return ResourceManager.GetString("LoginValidated_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCESOS.
        /// </summary>
        public static string Mail_accesos {
            get {
                return ResourceManager.GetString("Mail_accesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias por ser nuestro aliado en información de comercio exterior de latinoamérica y el mundo.
        /// </summary>
        public static string Mail_agradecimiento {
            get {
                return ResourceManager.GetString("Mail_agradecimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BENEFICIOS.
        /// </summary>
        public static string Mail_beneficios {
            get {
                return ResourceManager.GetString("Mail_beneficios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En breves momentos nos estaremos contactando para enviarte tus datos de acceso, y los beneficios del plan adquirido..
        /// </summary>
        public static string Mail_Contact_Msg {
            get {
                return ResourceManager.GetString("Mail_Contact_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de tu compra:.
        /// </summary>
        public static string Mail_Detail_Msg {
            get {
                return ResourceManager.GetString("Mail_Detail_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoritos por país.
        /// </summary>
        public static string Mail_fav_pais {
            get {
                return ResourceManager.GetString("Mail_fav_pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin:.
        /// </summary>
        public static string Mail_fin {
            get {
                return ResourceManager.GetString("Mail_fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos:.
        /// </summary>
        public static string Mail_grupos {
            get {
                return ResourceManager.GetString("Mail_grupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le sugerimos guardar este correo para recordar sus claves de acceso..
        /// </summary>
        public static string Mail_guardar_correo {
            get {
                return ResourceManager.GetString("Mail_guardar_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para que puedas disfrutas tu plan.
        /// </summary>
        public static string Mail_info_text1 {
            get {
                return ResourceManager.GetString("Mail_info_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to que acabas de adquirir te indicamos la siguiente información que te ayudará a tener la mejor experiencia de la plataforma..
        /// </summary>
        public static string Mail_info_text2 {
            get {
                return ResourceManager.GetString("Mail_info_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresos y Descargas.
        /// </summary>
        public static string Mail_ing_desc {
            get {
                return ResourceManager.GetString("Mail_ing_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para ingresar a Veritrade hágalo de la siguiente manera:.
        /// </summary>
        public static string Mail_ingreso_info {
            get {
                return ResourceManager.GetString("Mail_ingreso_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio:.
        /// </summary>
        public static string Mail_inicio {
            get {
                return ResourceManager.GetString("Mail_inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulos:.
        /// </summary>
        public static string Mail_modulos {
            get {
                return ResourceManager.GetString("Mail_modulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paises:.
        /// </summary>
        public static string Mail_paises {
            get {
                return ResourceManager.GetString("Mail_paises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraseña:.
        /// </summary>
        public static string Mail_pass {
            get {
                return ResourceManager.GetString("Mail_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantillas de Excel:.
        /// </summary>
        public static string Mail_plantillas_excel {
            get {
                return ResourceManager.GetString("Mail_plantillas_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membresia Anual.
        /// </summary>
        public static string Mail_Suscription_Msg {
            get {
                return ResourceManager.GetString("Mail_Suscription_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muchas gracias por tu preferencia..
        /// </summary>
        public static string Mail_Thank_Msg {
            get {
                return ResourceManager.GetString("Mail_Thank_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimado(a).
        /// </summary>
        public static string Mail_Title_Name {
            get {
                return ResourceManager.GetString("Mail_Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario:.
        /// </summary>
        public static string Mail_usuario {
            get {
                return ResourceManager.GetString("Mail_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIGENCIA.
        /// </summary>
        public static string Mail_vigencia {
            get {
                return ResourceManager.GetString("Mail_vigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Bienvenido(a)!.
        /// </summary>
        public static string Mail_Welcome_Title {
            get {
                return ResourceManager.GetString("Mail_Welcome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quiénes ayudamos.
        /// </summary>
        public static string MenuItem01 {
            get {
                return ResourceManager.GetString("MenuItem01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importadores.
        /// </summary>
        public static string MenuItem01_SubItem01 {
            get {
                return ResourceManager.GetString("MenuItem01_SubItem01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportadores.
        /// </summary>
        public static string MenuItem01_SubItem02 {
            get {
                return ResourceManager.GetString("MenuItem01_SubItem02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing y ventas.
        /// </summary>
        public static string MenuItem01_SubItem03 {
            get {
                return ResourceManager.GetString("MenuItem01_SubItem03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compradores locales.
        /// </summary>
        public static string MenuItem01_SubItem04 {
            get {
                return ResourceManager.GetString("MenuItem01_SubItem04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analistas.
        /// </summary>
        public static string MenuItem01_SubItem05 {
            get {
                return ResourceManager.GetString("MenuItem01_SubItem05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operadores logísticos.
        /// </summary>
        public static string MenuItem01_SubItem06 {
            get {
                return ResourceManager.GetString("MenuItem01_SubItem06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutoriales online.
        /// </summary>
        public static string MenuItem02 {
            get {
                return ResourceManager.GetString("MenuItem02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string MenuItem03 {
            get {
                return ResourceManager.GetString("MenuItem03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Países.
        /// </summary>
        public static string MenuItem04 {
            get {
                return ResourceManager.GetString("MenuItem04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes y Precios.
        /// </summary>
        public static string MenuItem05 {
            get {
                return ResourceManager.GetString("MenuItem05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string MenuItem06 {
            get {
                return ResourceManager.GetString("MenuItem06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contáctenos.
        /// </summary>
        public static string MenuItem07 {
            get {
                return ResourceManager.GetString("MenuItem07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string MenuItem08 {
            get {
                return ResourceManager.GetString("MenuItem08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar empresa.
        /// </summary>
        public static string MenuItem09 {
            get {
                return ResourceManager.GetString("MenuItem09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Producto.
        /// </summary>
        public static string MenuItem10 {
            get {
                return ResourceManager.GetString("MenuItem10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enero.
        /// </summary>
        public static string Mes01 {
            get {
                return ResourceManager.GetString("Mes01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Febrero.
        /// </summary>
        public static string Mes02 {
            get {
                return ResourceManager.GetString("Mes02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marzo.
        /// </summary>
        public static string Mes03 {
            get {
                return ResourceManager.GetString("Mes03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        public static string Mes04 {
            get {
                return ResourceManager.GetString("Mes04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayo.
        /// </summary>
        public static string Mes05 {
            get {
                return ResourceManager.GetString("Mes05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junio.
        /// </summary>
        public static string Mes06 {
            get {
                return ResourceManager.GetString("Mes06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julio.
        /// </summary>
        public static string Mes07 {
            get {
                return ResourceManager.GetString("Mes07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        public static string Mes08 {
            get {
                return ResourceManager.GetString("Mes08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Septiembre.
        /// </summary>
        public static string Mes09 {
            get {
                return ResourceManager.GetString("Mes09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octubre.
        /// </summary>
        public static string Mes10 {
            get {
                return ResourceManager.GetString("Mes10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noviembre.
        /// </summary>
        public static string Mes11 {
            get {
                return ResourceManager.GetString("Mes11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diciembre.
        /// </summary>
        public static string Mes12 {
            get {
                return ResourceManager.GetString("Mes12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has realizado una consulta gratis..
        /// </summary>
        public static string Message_FreeTrial_Modal_Part1 {
            get {
                return ResourceManager.GetString("Message_FreeTrial_Modal_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si deseas ver la información y funcionalidades completas ingresa a:.
        /// </summary>
        public static string Message_FreeTrial_Modal_Part2 {
            get {
                return ResourceManager.GetString("Message_FreeTrial_Modal_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Más leidos.
        /// </summary>
        public static string Most_Reads {
            get {
                return ResourceManager.GetString("Most_Reads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Todos].
        /// </summary>
        public static string Option_Filter_All {
            get {
                return ResourceManager.GetString("Option_Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País Origen.
        /// </summary>
        public static string OriginCountry_FormField_Label {
            get {
                return ResourceManager.GetString("OriginCountry_FormField_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otros.
        /// </summary>
        public static string Others_Text {
            get {
                return ResourceManager.GetString("Others_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar PDF.
        /// </summary>
        public static string Pdf_text {
            get {
                return ResourceManager.GetString("Pdf_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes Veritrade.
        /// </summary>
        public static string Planes_Veritrade {
            get {
                return ResourceManager.GetString("Planes_Veritrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;small&gt;Detalles de nuestros&lt;/small&gt; Planes.
        /// </summary>
        public static string Plans_Details_Title {
            get {
                return ResourceManager.GetString("Plans_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;small&gt;Planes&lt;/small&gt; Veritrade.
        /// </summary>
        public static string Plans_Title {
            get {
                return ResourceManager.GetString("Plans_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paises.
        /// </summary>
        public static string Plans_Title_Countries {
            get {
                return ResourceManager.GetString("Plans_Title_Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresos y Descargas.
        /// </summary>
        public static string Plans_Title_Downloads {
            get {
                return ResourceManager.GetString("Plans_Title_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantillas de Excel.
        /// </summary>
        public static string Plans_Title_Excel {
            get {
                return ResourceManager.GetString("Plans_Title_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoritos y Grupos.
        /// </summary>
        public static string Plans_Title_Favorites {
            get {
                return ResourceManager.GetString("Plans_Title_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion Comex.
        /// </summary>
        public static string Plans_Title_Information {
            get {
                return ResourceManager.GetString("Plans_Title_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulos.
        /// </summary>
        public static string Plans_Title_Modules {
            get {
                return ResourceManager.GetString("Plans_Title_Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes.
        /// </summary>
        public static string Plans_Title_Plans {
            get {
                return ResourceManager.GetString("Plans_Title_Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string Plans_Title_Price {
            get {
                return ResourceManager.GetString("Plans_Title_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string Plans_Title_Users {
            get {
                return ResourceManager.GetString("Plans_Title_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen del plan.
        /// </summary>
        public static string PlanSummary_Text {
            get {
                return ResourceManager.GetString("PlanSummary_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicado el.
        /// </summary>
        public static string Post_Publish {
            get {
                return ResourceManager.GetString("Post_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se encontraron.
        /// </summary>
        public static string RecordsFound_Text_Part1 {
            get {
                return ResourceManager.GetString("RecordsFound_Text_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registros.
        /// </summary>
        public static string RecordsFound_Text_Part2 {
            get {
                return ResourceManager.GetString("RecordsFound_Text_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo salío mal, inténtalo de nuevo más tarde.
        /// </summary>
        public static string Request_Error_Message {
            get {
                return ResourceManager.GetString("Request_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Request_Error_Title {
            get {
                return ResourceManager.GetString("Request_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su solicitud está siendo procesada y nos contactaremos a la brevedad con usted..
        /// </summary>
        public static string Request_Message {
            get {
                return ResourceManager.GetString("Request_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Contacto o Soporte.
        /// </summary>
        public static string Request_Text01 {
            get {
                return ResourceManager.GetString("Request_Text01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Cotización.
        /// </summary>
        public static string Request_Text02 {
            get {
                return ResourceManager.GetString("Request_Text02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Muchas gracias por su interés!.
        /// </summary>
        public static string Request_Title {
            get {
                return ResourceManager.GetString("Request_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es obligatorio.
        /// </summary>
        public static string Required_Text {
            get {
                return ResourceManager.GetString("Required_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su usuario ya alcanzó el máximo contratado de ingresos al mes..
        /// </summary>
        public static string rpta4 {
            get {
                return ResourceManager.GetString("rpta4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SINPROGRAMA.
        /// </summary>
        public static string rpta5 {
            get {
                return ResourceManager.GetString("rpta5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos, el ingreso desde esta máquina excede a la cantidad contratada..
        /// </summary>
        public static string rpta6 {
            get {
                return ResourceManager.GetString("rpta6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Search_Button {
            get {
                return ResourceManager.GetString("Search_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string Search_Form_BrandField {
            get {
                return ResourceManager.GetString("Search_Form_BrandField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted desea ver las.
        /// </summary>
        public static string Search_Form_Item01 {
            get {
                return ResourceManager.GetString("Search_Form_Item01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string Search_Form_Item02 {
            get {
                return ResourceManager.GetString("Search_Form_Item02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción Comercial.
        /// </summary>
        public static string Search_Form_Item03 {
            get {
                return ResourceManager.GetString("Search_Form_Item03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partida.
        /// </summary>
        public static string Search_Form_Item04 {
            get {
                return ResourceManager.GetString("Search_Form_Item04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importador.
        /// </summary>
        public static string Search_Form_Item05 {
            get {
                return ResourceManager.GetString("Search_Form_Item05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportador.
        /// </summary>
        public static string Search_Form_Item06 {
            get {
                return ResourceManager.GetString("Search_Form_Item06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        public static string Search_Form_Item07 {
            get {
                return ResourceManager.GetString("Search_Form_Item07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información en línea desde 01-ENE.-2012 hasta 30-ABR.-2017.
        /// </summary>
        public static string Search_Form_Item08 {
            get {
                return ResourceManager.GetString("Search_Form_Item08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        public static string Search_Form_Item09 {
            get {
                return ResourceManager.GetString("Search_Form_Item09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasta.
        /// </summary>
        public static string Search_Form_Item10 {
            get {
                return ResourceManager.GetString("Search_Form_Item10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En la prueba gratuita solo se muestran 03 meses de información.
        /// </summary>
        public static string Search_Form_Item11 {
            get {
                return ResourceManager.GetString("Search_Form_Item11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese al menos un filtro antes de dar clic al botón BUSCAR.
        /// </summary>
        public static string Search_Message_Modal {
            get {
                return ResourceManager.GetString("Search_Message_Modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablecer Buscador.
        /// </summary>
        public static string Search_ResetButton {
            get {
                return ResourceManager.GetString("Search_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda.
        /// </summary>
        public static string Search_Title_Modal {
            get {
                return ResourceManager.GetString("Search_Title_Modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor seleccione el(los) elemento(s) a Agregar como filtros.
        /// </summary>
        public static string SelectFilter_Message_Modal {
            get {
                return ResourceManager.GetString("SelectFilter_Message_Modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar &gt;.
        /// </summary>
        public static string Send_Button {
            get {
                return ResourceManager.GetString("Send_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para.
        /// </summary>
        public static string Service_Text_Title_For {
            get {
                return ResourceManager.GetString("Service_Text_Title_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección de Facturación 1.
        /// </summary>
        public static string Stripe_Form_BillingAddress {
            get {
                return ResourceManager.GetString("Stripe_Form_BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección de Facturación 2.
        /// </summary>
        public static string Stripe_Form_BillingAddress2 {
            get {
                return ResourceManager.GetString("Stripe_Form_BillingAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad de Facturación.
        /// </summary>
        public static string Stripe_Form_BillingCity {
            get {
                return ResourceManager.GetString("Stripe_Form_BillingCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País de Facturación.
        /// </summary>
        public static string Stripe_Form_BillingCountry {
            get {
                return ResourceManager.GetString("Stripe_Form_BillingCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de Facturación.
        /// </summary>
        public static string Stripe_Form_BillingState {
            get {
                return ResourceManager.GetString("Stripe_Form_BillingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titular de la tarjeta.
        /// </summary>
        public static string Stripe_Form_CardName {
            get {
                return ResourceManager.GetString("Stripe_Form_CardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de tarjeta.
        /// </summary>
        public static string Stripe_Form_CardNumber {
            get {
                return ResourceManager.GetString("Stripe_Form_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo de Seguridad.
        /// </summary>
        public static string Stripe_Form_Cvc {
            get {
                return ResourceManager.GetString("Stripe_Form_Cvc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección de Correo Electrónico.
        /// </summary>
        public static string Stripe_Form_Email {
            get {
                return ResourceManager.GetString("Stripe_Form_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Expiracion (MM/YY).
        /// </summary>
        public static string Stripe_Form_Expiry {
            get {
                return ResourceManager.GetString("Stripe_Form_Expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Teléfono.
        /// </summary>
        public static string Stripe_Form_Phone {
            get {
                return ResourceManager.GetString("Stripe_Form_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Postal.
        /// </summary>
        public static string Stripe_Form_Zip {
            get {
                return ResourceManager.GetString("Stripe_Form_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario y/o Contraseña incorrectos.
        /// </summary>
        public static string Success_title1 {
            get {
                return ResourceManager.GetString("Success_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario inactivo.
        /// </summary>
        public static string Success_title2 {
            get {
                return ResourceManager.GetString("Success_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Acceso no autorizado!.
        /// </summary>
        public static string Success_title3 {
            get {
                return ResourceManager.GetString("Success_title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡No se pudo ingresar al sistema!.
        /// </summary>
        public static string Success_title4 {
            get {
                return ResourceManager.GetString("Success_title4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Términos de Venta.
        /// </summary>
        public static string Terminos_Venta_Link {
            get {
                return ResourceManager.GetString("Terminos_Venta_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condiciones de Venta.
        /// </summary>
        public static string Terminos_Venta_Titulo {
            get {
                return ResourceManager.GetString("Terminos_Venta_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicita tu prueba gratuita.
        /// </summary>
        public static string Title_FreeTrial_Modal {
            get {
                return ResourceManager.GetString("Title_FreeTrial_Modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totales.
        /// </summary>
        public static string TotalsText {
            get {
                return ResourceManager.GetString("TotalsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prueba Gratis.
        /// </summary>
        public static string TrialText {
            get {
                return ResourceManager.GetString("TrialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de tarjeta.
        /// </summary>
        public static string TypeCard_Text {
            get {
                return ResourceManager.GetString("TypeCard_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturación en CLP al tipo de cambio del día.
        /// </summary>
        public static string Valor_Dolar {
            get {
                return ResourceManager.GetString("Valor_Dolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver detalles del plan.
        /// </summary>
        public static string ViewFeatures_Text {
            get {
                return ResourceManager.GetString("ViewFeatures_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escríbenos.
        /// </summary>
        public static string Wsp_msg {
            get {
                return ResourceManager.GetString("Wsp_msg", resourceCulture);
            }
        }
    }
}
