//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ValidationResource", typeof(ValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País es obligatorio.
        /// </summary>
        public static string Error_Country_Required {
            get {
                return ResourceManager.GetString("Error_Country_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección es obligatoria.
        /// </summary>
        public static string Error_Direccion_Required {
            get {
                return ResourceManager.GetString("Error_Direccion_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor ingresado no es una dirección de correo válida..
        /// </summary>
        public static string Error_Email_EmailAddress {
            get {
                return ResourceManager.GetString("Error_Email_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico ya existe.
        /// </summary>
        public static string Error_Email_Exist {
            get {
                return ResourceManager.GetString("Error_Email_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo es obligatorio.
        /// </summary>
        public static string Error_Email_Required {
            get {
                return ResourceManager.GetString("Error_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre es requerido.
        /// </summary>
        public static string Error_FirstName_Required {
            get {
                return ResourceManager.GetString("Error_FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo es obligatorio.
        /// </summary>
        public static string Error_FullName_Required {
            get {
                return ResourceManager.GetString("Error_FullName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo debe tener entre 7 a 40 caracteres.
        /// </summary>
        public static string Error_FullName_StringLength {
            get {
                return ResourceManager.GetString("Error_FullName_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo es obligatorio.
        /// </summary>
        public static string Error_General_Required {
            get {
                return ResourceManager.GetString("Error_General_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos es requerido.
        /// </summary>
        public static string Error_LastName_Required {
            get {
                return ResourceManager.GetString("Error_LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje es obligatorio.
        /// </summary>
        public static string Error_Message_Required {
            get {
                return ResourceManager.GetString("Error_Message_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres y Apellidos es obligatorio.
        /// </summary>
        public static string Error_Names_Required {
            get {
                return ResourceManager.GetString("Error_Names_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del teléfono incorrecto.
        /// </summary>
        public static string Error_Phone_RegularExpression {
            get {
                return ResourceManager.GetString("Error_Phone_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono es obligatorio.
        /// </summary>
        public static string Error_Phone_Required {
            get {
                return ResourceManager.GetString("Error_Phone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono debe tener entre 7 a 12 caracteres..
        /// </summary>
        public static string Error_Phone_StringLength {
            get {
                return ResourceManager.GetString("Error_Phone_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono no válido.
        /// </summary>
        public static string Error_Phone_Valid {
            get {
                return ResourceManager.GetString("Error_Phone_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razon Social es obligatoria.
        /// </summary>
        public static string Error_RazonSocial_Required {
            get {
                return ResourceManager.GetString("Error_RazonSocial_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUC es obligatorio.
        /// </summary>
        public static string Error_Ruc_Required {
            get {
                return ResourceManager.GetString("Error_Ruc_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ud. debe estar de acuerdo con nuestros Términos y Condiciones..
        /// </summary>
        public static string Error_TermsConditions_Required {
            get {
                return ResourceManager.GetString("Error_TermsConditions_Required", resourceCulture);
            }
        }
    }
}
