//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Veritrade2018.SentinelPeru {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SentinelWS02SoapBinding", Namespace="AFPrivado")]
    public partial class SentinelWS02 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExecuteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SentinelWS02() {
            this.Url = global::Veritrade2018.Properties.Settings.Default.Veritrade2018_SentinelPeru_SentinelWS02;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExecuteCompletedEventHandler ExecuteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("AFPrivadoaction/ASENTINELWS02.Execute", RequestElementName="SentinelWS02.Execute", RequestNamespace="AFPrivado", ResponseElementName="SentinelWS02.ExecuteResponse", ResponseNamespace="AFPrivado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Cnsdtconrapsms")]
        public CNSDTConRapWS Execute(string Usuario, string Password, long Servicio, string Tipodoc, string Nrodoc) {
            object[] results = this.Invoke("Execute", new object[] {
                        Usuario,
                        Password,
                        Servicio,
                        Tipodoc,
                        Nrodoc});
            return ((CNSDTConRapWS)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteAsync(string Usuario, string Password, long Servicio, string Tipodoc, string Nrodoc) {
            this.ExecuteAsync(Usuario, Password, Servicio, Tipodoc, Nrodoc, null);
        }
        
        /// <remarks/>
        public void ExecuteAsync(string Usuario, string Password, long Servicio, string Tipodoc, string Nrodoc, object userState) {
            if ((this.ExecuteOperationCompleted == null)) {
                this.ExecuteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteOperationCompleted);
            }
            this.InvokeAsync("Execute", new object[] {
                        Usuario,
                        Password,
                        Servicio,
                        Tipodoc,
                        Nrodoc}, this.ExecuteOperationCompleted, userState);
        }
        
        private void OnExecuteOperationCompleted(object arg) {
            if ((this.ExecuteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteCompleted(this, new ExecuteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="AFPrivado")]
    public partial class CNSDTConRapWS {
        
        private string documentoField;
        
        private string razonSocialField;
        
        private System.Nullable<System.DateTime> fechaProcesoField;
        
        private string semaforosField;
        
        private string scoreField;
        
        private string nroBancosField;
        
        private string deudaTotalField;
        
        private string vencidoBancoField;
        
        private string calificativoField;
        
        private string veces24mField;
        
        private double scorePromedioField;
        
        private string semaActualField;
        
        private string semaPrevioField;
        
        private string semaPeorMejorField;
        
        private string documento2Field;
        
        private string estDomicField;
        
        private string condDomicField;
        
        private string deudaTributariaField;
        
        private string deudaLaboralField;
        
        private string deudaImpagaField;
        
        private string deudaProtestosField;
        
        private string deudaSBSField;
        
        private string tarCtasField;
        
        private string repNegField;
        
        private string tipoActvField;
        
        private string fechIniActvField;
        
        private string codigoWSField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string RazonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> FechaProceso {
            get {
                return this.fechaProcesoField;
            }
            set {
                this.fechaProcesoField = value;
            }
        }
        
        /// <remarks/>
        public string Semaforos {
            get {
                return this.semaforosField;
            }
            set {
                this.semaforosField = value;
            }
        }
        
        /// <remarks/>
        public string Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        public string NroBancos {
            get {
                return this.nroBancosField;
            }
            set {
                this.nroBancosField = value;
            }
        }
        
        /// <remarks/>
        public string DeudaTotal {
            get {
                return this.deudaTotalField;
            }
            set {
                this.deudaTotalField = value;
            }
        }
        
        /// <remarks/>
        public string VencidoBanco {
            get {
                return this.vencidoBancoField;
            }
            set {
                this.vencidoBancoField = value;
            }
        }
        
        /// <remarks/>
        public string Calificativo {
            get {
                return this.calificativoField;
            }
            set {
                this.calificativoField = value;
            }
        }
        
        /// <remarks/>
        public string Veces24m {
            get {
                return this.veces24mField;
            }
            set {
                this.veces24mField = value;
            }
        }
        
        /// <remarks/>
        public double ScorePromedio {
            get {
                return this.scorePromedioField;
            }
            set {
                this.scorePromedioField = value;
            }
        }
        
        /// <remarks/>
        public string SemaActual {
            get {
                return this.semaActualField;
            }
            set {
                this.semaActualField = value;
            }
        }
        
        /// <remarks/>
        public string SemaPrevio {
            get {
                return this.semaPrevioField;
            }
            set {
                this.semaPrevioField = value;
            }
        }
        
        /// <remarks/>
        public string SemaPeorMejor {
            get {
                return this.semaPeorMejorField;
            }
            set {
                this.semaPeorMejorField = value;
            }
        }
        
        /// <remarks/>
        public string Documento2 {
            get {
                return this.documento2Field;
            }
            set {
                this.documento2Field = value;
            }
        }
        
        /// <remarks/>
        public string EstDomic {
            get {
                return this.estDomicField;
            }
            set {
                this.estDomicField = value;
            }
        }
        
        /// <remarks/>
        public string CondDomic {
            get {
                return this.condDomicField;
            }
            set {
                this.condDomicField = value;
            }
        }
        
        /// <remarks/>
        public string DeudaTributaria {
            get {
                return this.deudaTributariaField;
            }
            set {
                this.deudaTributariaField = value;
            }
        }
        
        /// <remarks/>
        public string DeudaLaboral {
            get {
                return this.deudaLaboralField;
            }
            set {
                this.deudaLaboralField = value;
            }
        }
        
        /// <remarks/>
        public string DeudaImpaga {
            get {
                return this.deudaImpagaField;
            }
            set {
                this.deudaImpagaField = value;
            }
        }
        
        /// <remarks/>
        public string DeudaProtestos {
            get {
                return this.deudaProtestosField;
            }
            set {
                this.deudaProtestosField = value;
            }
        }
        
        /// <remarks/>
        public string DeudaSBS {
            get {
                return this.deudaSBSField;
            }
            set {
                this.deudaSBSField = value;
            }
        }
        
        /// <remarks/>
        public string TarCtas {
            get {
                return this.tarCtasField;
            }
            set {
                this.tarCtasField = value;
            }
        }
        
        /// <remarks/>
        public string RepNeg {
            get {
                return this.repNegField;
            }
            set {
                this.repNegField = value;
            }
        }
        
        /// <remarks/>
        public string TipoActv {
            get {
                return this.tipoActvField;
            }
            set {
                this.tipoActvField = value;
            }
        }
        
        /// <remarks/>
        public string FechIniActv {
            get {
                return this.fechIniActvField;
            }
            set {
                this.fechIniActvField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoWS {
            get {
                return this.codigoWSField;
            }
            set {
                this.codigoWSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ExecuteCompletedEventHandler(object sender, ExecuteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CNSDTConRapWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CNSDTConRapWS)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591