//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Veritrade2017.VeritradeServicios {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosCorreoSoap", Namespace="http://VERIDEV/")]
    public partial class ServiciosCorreo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EnviaEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviaEmail2OperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviaEmail3OperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviaVerinewsOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviaVerinews2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosCorreo() {
            this.Url = global::Veritrade2017.Properties.Settings.Default.Veritrade2017_VeritradeServicios_ServiciosCorreo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EnviaEmailCompletedEventHandler EnviaEmailCompleted;
        
        /// <remarks/>
        public event EnviaEmail2CompletedEventHandler EnviaEmail2Completed;
        
        /// <remarks/>
        public event EnviaEmail3CompletedEventHandler EnviaEmail3Completed;
        
        /// <remarks/>
        public event EnviaVerinewsCompletedEventHandler EnviaVerinewsCompleted;
        
        /// <remarks/>
        public event EnviaVerinews2CompletedEventHandler EnviaVerinews2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://VERIDEV/EnviaEmail", RequestNamespace="http://VERIDEV/", ResponseNamespace="http://VERIDEV/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviaEmail(string FromName, string FromEmail, string ToName, string ToEmail, string Subject, string URL) {
            object[] results = this.Invoke("EnviaEmail", new object[] {
                        FromName,
                        FromEmail,
                        ToName,
                        ToEmail,
                        Subject,
                        URL});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviaEmailAsync(string FromName, string FromEmail, string ToName, string ToEmail, string Subject, string URL) {
            this.EnviaEmailAsync(FromName, FromEmail, ToName, ToEmail, Subject, URL, null);
        }
        
        /// <remarks/>
        public void EnviaEmailAsync(string FromName, string FromEmail, string ToName, string ToEmail, string Subject, string URL, object userState) {
            if ((this.EnviaEmailOperationCompleted == null)) {
                this.EnviaEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviaEmailOperationCompleted);
            }
            this.InvokeAsync("EnviaEmail", new object[] {
                        FromName,
                        FromEmail,
                        ToName,
                        ToEmail,
                        Subject,
                        URL}, this.EnviaEmailOperationCompleted, userState);
        }
        
        private void OnEnviaEmailOperationCompleted(object arg) {
            if ((this.EnviaEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviaEmailCompleted(this, new EnviaEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://VERIDEV/EnviaEmail2", RequestNamespace="http://VERIDEV/", ResponseNamespace="http://VERIDEV/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviaEmail2(string FromName, string FromEmail, string ToName, string ToEmail, string Subject, string URL, string EmailEnvio1, string EmailEnvioPassword1) {
            object[] results = this.Invoke("EnviaEmail2", new object[] {
                        FromName,
                        FromEmail,
                        ToName,
                        ToEmail,
                        Subject,
                        URL,
                        EmailEnvio1,
                        EmailEnvioPassword1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviaEmail2Async(string FromName, string FromEmail, string ToName, string ToEmail, string Subject, string URL, string EmailEnvio1, string EmailEnvioPassword1) {
            this.EnviaEmail2Async(FromName, FromEmail, ToName, ToEmail, Subject, URL, EmailEnvio1, EmailEnvioPassword1, null);
        }
        
        /// <remarks/>
        public void EnviaEmail2Async(string FromName, string FromEmail, string ToName, string ToEmail, string Subject, string URL, string EmailEnvio1, string EmailEnvioPassword1, object userState) {
            if ((this.EnviaEmail2OperationCompleted == null)) {
                this.EnviaEmail2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviaEmail2OperationCompleted);
            }
            this.InvokeAsync("EnviaEmail2", new object[] {
                        FromName,
                        FromEmail,
                        ToName,
                        ToEmail,
                        Subject,
                        URL,
                        EmailEnvio1,
                        EmailEnvioPassword1}, this.EnviaEmail2OperationCompleted, userState);
        }
        
        private void OnEnviaEmail2OperationCompleted(object arg) {
            if ((this.EnviaEmail2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviaEmail2Completed(this, new EnviaEmail2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://VERIDEV/EnviaEmail3", RequestNamespace="http://VERIDEV/", ResponseNamespace="http://VERIDEV/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviaEmail3(string FromName, string FromEmail, string ToName, string ToEmail, string CcName, string CcEmail, string BccName, string BccEmail, string Subject, string URL, string EmailEnvio1, string EmailEnvioPassword1) {
            object[] results = this.Invoke("EnviaEmail3", new object[] {
                        FromName,
                        FromEmail,
                        ToName,
                        ToEmail,
                        CcName,
                        CcEmail,
                        BccName,
                        BccEmail,
                        Subject,
                        URL,
                        EmailEnvio1,
                        EmailEnvioPassword1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviaEmail3Async(string FromName, string FromEmail, string ToName, string ToEmail, string CcName, string CcEmail, string BccName, string BccEmail, string Subject, string URL, string EmailEnvio1, string EmailEnvioPassword1) {
            this.EnviaEmail3Async(FromName, FromEmail, ToName, ToEmail, CcName, CcEmail, BccName, BccEmail, Subject, URL, EmailEnvio1, EmailEnvioPassword1, null);
        }
        
        /// <remarks/>
        public void EnviaEmail3Async(string FromName, string FromEmail, string ToName, string ToEmail, string CcName, string CcEmail, string BccName, string BccEmail, string Subject, string URL, string EmailEnvio1, string EmailEnvioPassword1, object userState) {
            if ((this.EnviaEmail3OperationCompleted == null)) {
                this.EnviaEmail3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviaEmail3OperationCompleted);
            }
            this.InvokeAsync("EnviaEmail3", new object[] {
                        FromName,
                        FromEmail,
                        ToName,
                        ToEmail,
                        CcName,
                        CcEmail,
                        BccName,
                        BccEmail,
                        Subject,
                        URL,
                        EmailEnvio1,
                        EmailEnvioPassword1}, this.EnviaEmail3OperationCompleted, userState);
        }
        
        private void OnEnviaEmail3OperationCompleted(object arg) {
            if ((this.EnviaEmail3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviaEmail3Completed(this, new EnviaEmail3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://VERIDEV/EnviaVerinews", RequestNamespace="http://VERIDEV/", ResponseNamespace="http://VERIDEV/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviaVerinews(string ToName, string ToEmail, string Subject, string URL) {
            object[] results = this.Invoke("EnviaVerinews", new object[] {
                        ToName,
                        ToEmail,
                        Subject,
                        URL});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviaVerinewsAsync(string ToName, string ToEmail, string Subject, string URL) {
            this.EnviaVerinewsAsync(ToName, ToEmail, Subject, URL, null);
        }
        
        /// <remarks/>
        public void EnviaVerinewsAsync(string ToName, string ToEmail, string Subject, string URL, object userState) {
            if ((this.EnviaVerinewsOperationCompleted == null)) {
                this.EnviaVerinewsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviaVerinewsOperationCompleted);
            }
            this.InvokeAsync("EnviaVerinews", new object[] {
                        ToName,
                        ToEmail,
                        Subject,
                        URL}, this.EnviaVerinewsOperationCompleted, userState);
        }
        
        private void OnEnviaVerinewsOperationCompleted(object arg) {
            if ((this.EnviaVerinewsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviaVerinewsCompleted(this, new EnviaVerinewsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://VERIDEV/EnviaVerinews2", RequestNamespace="http://VERIDEV/", ResponseNamespace="http://VERIDEV/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviaVerinews2(string ToName, string ToEmail, string Subject, string URL, string EmailEnvio1, string EmailEnvioNombre1, string EmailEnvioPassword1) {
            object[] results = this.Invoke("EnviaVerinews2", new object[] {
                        ToName,
                        ToEmail,
                        Subject,
                        URL,
                        EmailEnvio1,
                        EmailEnvioNombre1,
                        EmailEnvioPassword1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviaVerinews2Async(string ToName, string ToEmail, string Subject, string URL, string EmailEnvio1, string EmailEnvioNombre1, string EmailEnvioPassword1) {
            this.EnviaVerinews2Async(ToName, ToEmail, Subject, URL, EmailEnvio1, EmailEnvioNombre1, EmailEnvioPassword1, null);
        }
        
        /// <remarks/>
        public void EnviaVerinews2Async(string ToName, string ToEmail, string Subject, string URL, string EmailEnvio1, string EmailEnvioNombre1, string EmailEnvioPassword1, object userState) {
            if ((this.EnviaVerinews2OperationCompleted == null)) {
                this.EnviaVerinews2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviaVerinews2OperationCompleted);
            }
            this.InvokeAsync("EnviaVerinews2", new object[] {
                        ToName,
                        ToEmail,
                        Subject,
                        URL,
                        EmailEnvio1,
                        EmailEnvioNombre1,
                        EmailEnvioPassword1}, this.EnviaVerinews2OperationCompleted, userState);
        }
        
        private void OnEnviaVerinews2OperationCompleted(object arg) {
            if ((this.EnviaVerinews2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviaVerinews2Completed(this, new EnviaVerinews2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EnviaEmailCompletedEventHandler(object sender, EnviaEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviaEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviaEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EnviaEmail2CompletedEventHandler(object sender, EnviaEmail2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviaEmail2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviaEmail2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EnviaEmail3CompletedEventHandler(object sender, EnviaEmail3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviaEmail3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviaEmail3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EnviaVerinewsCompletedEventHandler(object sender, EnviaVerinewsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviaVerinewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviaVerinewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EnviaVerinews2CompletedEventHandler(object sender, EnviaVerinews2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviaVerinews2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviaVerinews2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591